### ISSUE TITLE
Launch tracking

### ISSUE THREAD

**Issue by kytrinyx** [exercism/abap#1]
Edit this issue to keep track of the tasks you're working on towards launch.

We have a rough guide for how to launch a track, which is sorely outdated but
quite possibly better than nothing (I'm so sorry, I'm waaaay behind on getting
documentation updated).
https://github.com/exercism/legacy-docs/blob/main/language-tracks/launch/README.md

Check out https://github.com/orgs/exercism/teams/track-maintainers/discussions/1
for details about the #maintaining-\<track\> channels and private #maintainers channel in the exercism-team Slack workspace.

Please ask if you have any questions or if anything is confusing!

**Comment by iHiD** [comment]
cc @larshp Here you go! :) You should have an invite to join the team.  I'd suggest arranging a chat with @erikschierboom to plan this out. Are there any co-maintainers?

---

cc @erikschierboom - This repo will need updating too.

**Comment by larshp** [comment]
thanks, I got the invite, will have a look, but a bit short on time this weekend 😅

**Comment by larshp** [comment]
co-maintainers:
@mbtools
@g-back

**Comment by iHiD** [comment]
Both of those have been invited.

**Comment by ErikSchierboom** [comment]
We have just updated the documentation for building a new track! Below you'll find a list of the various tasks you'll work on to implement the track.

- [ ] [Join our community](https://exercism.org/docs/building/tracks/new/join-our-community)
- [ ] [Select programming language variant](https://exercism.org/docs/building/tracks/new/select-programming-language-variant) (if applicable)
- [ ] [Select testing framework](https://exercism.org/docs/building/tracks/new/select-testing-framework)
- [ ] [Add the first exercise](https://exercism.org/docs/building/tracks/new/add-first-exercise)
- [ ] [Add initial exercises](https://exercism.org/docs/building/tracks/new/add-initial-exercises)
- [ ] [Setup Continuous Integration](https://exercism.org/docs/building/tracks/new/setup-continuous-integration)
- [ ] [Prepare for launch](https://exercism.org/docs/building/tracks/new/prepare-for-launch)
- [ ] [Find Maintainers](https://exercism.org/docs/building/tracks/new/find-maintainers)
- [ ] [Launch!](https://exercism.org/docs/building/tracks/new/launch)
- [ ] [Implement tooling](https://exercism.org/docs/building/tracks/new/implement-tooling)
- [ ] [Prepare for open source contributions from strangers](https://exercism.org/docs/building/tracks/new/prepare-for-contributions)

Note: as the documentation is brand new™, there might be things that are unclear. Please let us know of any such things, and we'll fix them!

@kytrinyx If you feel like this is useful, you could consider copy/pasting this list in your opening post.

**Comment by larshp** [comment]
todo: implement 20+ other exercises

currently 9 exercises implemented

**Comment by iHiD** [comment]
Great progress!

**Comment by ErikSchierboom** [comment]
Indeed!

**Comment by larshp** [comment]
@iHiD can you help inviting @pokrakam and @marianfoo as maintainers of this repository?

**Comment by larshp** [comment]
Now at 21 exercises

Test runner running, CI setup

Multiple maintainers

would like to get https://github.com/exercism/exercism/issues/6186 fixed before launch, and probably https://github.com/exercism/abap-test-runner/issues/38

**Comment by ErikSchierboom** [comment]
Great stuff!

**Comment by larshp** [comment]
@iHiD can you help inviting @pokrakam and @marianfoo as maintainers of this repository? 

I guess due to https://github.com/exercism/website/pull/2438 they cannot access the content anymore

**Comment by iHiD** [comment]
Hi @larshp. Sure! I'll add them with write-permission to this repo, but I'd rather not add people as full maintainers until they've contributed, as doing so also gives permissions to other parts of the Exercism ecosystem.

Hi everyone! 🙂

**Comment by larshp** [comment]
yea, I understand, but on the other side https://github.com/exercism/website/pull/2438 closes inactive tracks for everyone not maintainer, so its difficult to contribute to something that is not visible 🤷‍♂️

**Comment by iHiD** [comment]
@larshp Yep, for sure. Maybe something we need to think about more generally (we probably want a `beta` role), but for now Erik's manually enabled that for the people you mentioned.

**Comment by pokrakam** [comment]
FWIW, @marianfoo and myself have already contributed.

**Comment by iHiD** [comment]
@pokrakam Thank you 🙂 I'm totally happy for you all to have write access to this repo to build things out.

We have thousands of contributors that contribute code, content and exercises, but only a few are committed enough to warrant maintainer status, and get the kudos and permissions that that entails. So last year we put a fixed process in place for the journey to become and staying as a maintainer. You can read it all here: https://exercism.org/docs/community/maintainers

**Comment by pokrakam** [comment]
@iHiD Thanks, my comment was in response to "_rather not add people as full maintainers until they've contributed_", but contributor is perfectly sufficient 🙂 As far as maintainer goes my available time is probably too sporadic, we'll see how it goes.

**Comment by larshp** [comment]
cool, I think everything is set for launch?

will setting active to true work, as described in https://exercism.org/docs/building/tracks/new/launch ?

I think we would like to set a launch date sometime in the future, so we can make a bit of fuzz about it

**Comment by ErikSchierboom** [comment]
Yes, almost :) One minor thing that is missing are the key features: https://exercism.org/docs/building/tracks/config-json#key-features

> I think we would like to set a launch date sometime in the future, so we can make a bit of fuzz about it

You can release the track anytime when you merge a PR to set `active` to `true`. Some buzz sounds good!
