### ISSUE TITLE
Darts: arithmetic power operator ** leads to wrong results

### ISSUE THREAD

**Issue by agoeb** [exercism/abap#109]
While doing the [Darts exercise](https://exercism.org/tracks/abap/exercises/darts) I tried using the `**` operator like this:

`distance = sqrt( x ** 2 + y ** 2 ).`

This led to test failures unless forcing operator precedence using

`distance = sqrt( ( x ** 2 ) + ( y ** 2 ) ).`

It seems the abapLint transpiler handles operator precedence different from the ABAP runtime, just evaluating the expression from left to right.

### Minimal example

```
data n type i.
n = 3 ** 2 + 2 ** 2.
write / n.
```

AS ABAP: `3 ** 2 + 2 ** 2` = `9 + 4` = `13`.
Transpiler: `3 ** 2 + 2 ** 2` --> `power(add(power(3,2),2),2)` --> `(9 + 2) ** 2` = `121`.

**Comment by larshp** [comment]
https://github.com/abaplint/transpiler/pull/687/commits/e8476dac1d79613181deb37003c0aadf5dfbdaf6

**Comment by larshp** [comment]
@agoeb try again, exercism runner updated

**Comment by agoeb** [comment]
Works as expected. Unbelievably fast! 
I guess I'm supposed to close the issue now.
Thanks a lot!
