### ISSUE TITLE
Error "FIND, runtime, no input, s empty" in the Scrabble Score exercise

### ISSUE THREAD

**Issue by BaerbelW** [exercism/abap#112]
When trying to test the below code, I get the error "FIND, runtime, no input, s empty". The issue may will be on my end as I'm not used to working with ABAP outside an ABAP-editor with all the language support that provides!

```abap
CLASS zcl_scrabble_score DEFINITION PUBLIC .

  PUBLIC SECTION.
    METHODS: score
               IMPORTING input         TYPE string OPTIONAL
               RETURNING VALUE(result) TYPE i.
  PROTECTED SECTION.
  PRIVATE SECTION.
    types: begin of ty_scores,
             letters(10)    type c,
             score          type i,
           end  of ty_scores.
    data: defined_scores type standard table of ty_scores.
    data: def_score  type ty_scores.         

ENDCLASS.

CLASS zcl_scrabble_score IMPLEMENTATION.

  METHOD score.
     data: letter(1) type c,
           clen      type i.

     check input is not initial.

     defined_scores = VALUE #( ( letters = 'AEIOULNRST' score = 1 )
                       ( letters = 'DG' score = 2 )
                       ( letters = 'BCMP' score = 3 )
                       ( letters = 'FHVWY' score = 4 )
                       ( letters = 'K' score = 5 )
                       ( letters = 'JX' score = 8 )
                       ( letters = 'QZ' score = 10 ) ).

    "DESCRIBE FIELD input LENGTH DATA(clen) IN CHARACTER MODE.
    clen = strlen( input ).

    Do clen times.
      letter = input+sy-index(1).  "substring( val = input off = sy-index len = 1 ).
      loop at defined_scores INTO data(letterscore).
        FIND letter IN letterscore-letters.
        IF sy-subrc EQ 0.
          result = result + letterscore-score.
          exit.
        ENDIF.
      endloop.
    enddo.

  ENDMETHOD.

ENDCLASS.
```

**Comment by larshp** [comment]
thanks, I've reproduced the error as below, bug in transpiler runtime...
![image](https://user-images.githubusercontent.com/5888506/161373353-ee880b05-e0f4-47e6-97ec-1b7a9bfc2747.png)

**Comment by larshp** [comment]
https://github.com/exercism/abap/pull/82 will hopefully make it easier to pull the code into a SAP ABAP system

having debugging would be nice too, however its not part of the Exercism platform as such

F1 help: yea, perhaps we can do that somehow 😅

**Comment by pokrakam** [comment]
Hi @BaerbelW you can always write it on an SAP system and paste the code here once it's running. 
As Lars already pointed out we are attempting to join the Exercism format with abapGit. 

Alternatively I've also created a repo https://github.com/pokrakam/exercism-abap-local from which you can also pull the entire set of empty exercises with test classes into one package using abapGit.

**Comment by BaerbelW** [comment]
Thanks, Lars & Mike!

I plan to use good old copy & paste to recreate the code in one of our sandbox systems - we don't really use ABAPGit (yet). I'll however not have a means to do that over the weekend as our sandbox and development systems are not available then. So, for now, I'm "running blind" (and realize how much I depend on language support for even simple ABAP exercises!).

**Comment by BaerbelW** [comment]
Something must have changed in the meantime as I no longer get the error mentioned in the OP. I'm now passing 7 and fail 4 tests but can't make heads or tails of why four fail - esp. as the one getting a complete tally for all letters is among the passed tests. How can the logic be correct for the overall number but fail for some others for shorter input? Guess, I'll have to wait until next week and copy the code into a sandbox system to then take a look via debugging to figure out which stupid mistake is still in my code! We sure are spoiled with the tools available in an SAP-system, aren't we?!?

**Comment by larshp** [comment]
yes, I updated the runner earlier today, https://github.com/exercism/abap-test-runner

line `letter = input+sy-index(1).`, the index starts at 1, but I guess you want to start with the first character?

**Comment by BaerbelW** [comment]
Thanks, Lars!

I had already changed that statement to use SUBSTR instead, but forgot that the offset for the first letter is 0 and not 1. Once I updated that, all tests were passed.

**Comment by larshp** [comment]
cool

I also opened https://github.com/abaplint/transpiler/issues/689, as it currently does not throw the correct exception, I think that would have helped identifying the error

**Comment by larshp** [comment]
closing, running, [BaerbelW](https://github.com/BaerbelW) feel free to reopen if something is missing
