### ISSUE TITLE
Error occured in exercise "ATBASH CIPHER"

### ISSUE THREAD

**Issue by shafiq2601** [exercism/abap#115]
It runs without issues on my SAP system but fails in exercism editor with following errors:

> We received the following error when we ran your code:
TypeError: Cannot read properties of undefined (reading 'get')
    at zcl_atbash_cipher.translate (file:///tmp/exercism-abap-runner-21XJjM/compiled/zcl_atbash_cipher.clas.mjs:29:112)
    at zcl_atbash_cipher.encode (file:///tmp/exercism-abap-runner-21XJjM/compiled/zcl_atbash_cipher.clas.mjs:53:32)
    at ltcl_test.encode1 (file:///tmp/exercism-abap-runner-21XJjM/compiled/zcl_atbash_cipher.clas.testclasses.mjs:15:91)
    at Function.run (file:///tmp/exercism-abap-runner-21XJjM/compiled/kernel_unit_runner.clas.mjs:126:77)
    at async run (file:///tmp/exercism-abap-runner-21XJjM/compiled/index_open.mjs:59:17)

Here is my code:

```abap
CLASS zcl_atbash_cipher DEFINITION PUBLIC FINAL CREATE PUBLIC.

  PUBLIC SECTION.
    METHODS decode
      IMPORTING
        cipher_text       TYPE string
      RETURNING
        VALUE(plain_text) TYPE string .
    METHODS encode
      IMPORTING
        plain_text         TYPE string
      RETURNING
        VALUE(cipher_text) TYPE string .
  PROTECTED SECTION.
  PRIVATE SECTION.
    METHODS translate IMPORTING input            TYPE string
                                local_dictionary TYPE string
                      RETURNING VALUE(result)    TYPE string.
ENDCLASS.



CLASS zcl_atbash_cipher IMPLEMENTATION.
  METHOD translate.
    result = REDUCE string( INIT str TYPE string
                  FOR i = 0 UNTIL i = strlen( input )
                  NEXT str = |{ str }{
                    COND #( LET  current_char       = to_upper( input+i(1) )
                                 foreign_dictionary = reverse( local_dictionary ) IN
                    WHEN local_dictionary   CS current_char
                    THEN to_lower( foreign_dictionary+sy-fdpos(1) )
                    WHEN '0123456789' CS current_char
                    THEN current_char ) }| ).
  ENDMETHOD.
  METHOD decode.
    plain_text = translate( input             = cipher_text
                            local_dictionary  = reverse( sy-abcde ) ).
  ENDMETHOD.

  METHOD encode.
    cipher_text = translate( input            = plain_text
                             local_dictionary = CONV #( sy-abcde ) ).
    REPLACE ALL OCCURRENCES OF REGEX `.{5}` IN cipher_text WITH |$& |.
    SHIFT cipher_text RIGHT DELETING TRAILING ` `.
    CONDENSE cipher_text.
  ENDMETHOD.
ENDCLASS.
```

**Comment by larshp** [comment]
might be similar problem as https://github.com/exercism/abap/issues/116

**Comment by larshp** [comment]
downport issue, `str` getting wrong type

![image](https://user-images.githubusercontent.com/5888506/162563430-78ed7c9d-41c6-42a1-8a21-e02d399997e0.png)

**Comment by larshp** [comment]
https://github.com/abaplint/abaplint/pull/2492/commits/dae7541727afe241a2c58af9ebfcd43d623342fe

**Comment by larshp** [comment]
![image](https://user-images.githubusercontent.com/5888506/162607007-4be13b35-f98e-4fcc-8b9d-46af5e9636d2.png)

**Comment by larshp** [comment]
reproduced as   

```abap
  DATA text TYPE string.
  text = |foo |.
  SHIFT text RIGHT DELETING TRAILING ` `.
  ASSERT text = | foo|.
```

**Comment by larshp** [comment]
https://github.com/abaplint/transpiler/pull/707

**Comment by larshp** [comment]
https://github.com/abaplint/transpiler/pull/708

**Comment by shafiq2601** [comment]
Thank you @larshp. I was able to submit this exercise. And with that I have submitted 23 out of the 24 exercises. There is just one last remaining: MINESWEEPER. i am sure that issue will also be taken care of soon.
