### ISSUE TITLE
Error occured in Exercise "KINDERGARTEN"

### ISSUE THREAD

**Issue by shafiq2601** [exercism/abap#118]
It runs without issues on my SAP system but fails in exercism editor with following errors:

> We received the following error when we ran your code:
./zcl_kindergarten_garden.clas.abap[45, 9] - Statement does not exist in ABAPopen-abap(or a parser error), "temp4" (parser_error) [E]
abaplint: 1 issue(s) found

Here is my code:
```abap
CLASS zcl_kindergarten_garden DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .
  PUBLIC SECTION.
    METHODS plants
      IMPORTING
        diagram        TYPE string
        student        TYPE string
      RETURNING
        VALUE(results) TYPE string_table.
  PROTECTED SECTION.
  PRIVATE SECTION.
    DATA students TYPE string_table.
ENDCLASS.
CLASS zcl_kindergarten_garden IMPLEMENTATION.
  METHOD plants.
    SPLIT diagram AT `\n` INTO TABLE DATA(lt_plants).
    DATA(lv_first_pos) = COND i( WHEN sy-abcde CS student+0(1) THEN sy-fdpos * 2 ).
    DO 2 TIMES.
      APPEND LINES OF VALUE string_table(
        FOR i = 0 UNTIL i = 2 (
         SWITCH #( substring( val = lt_plants[ sy-index ] off = lv_first_pos + i len = 1 )
          WHEN 'C' THEN 'clover'
          WHEN 'G' THEN 'grass'
          WHEN 'R' THEN 'radishes'
          WHEN 'V' THEN 'violets' ) ) ) TO results.
    ENDDO.
  ENDMETHOD.
ENDCLASS.
```

**Comment by larshp** [comment]
first fix, setting sy-fdpos, https://github.com/abaplint/transpiler/pull/696

**Comment by pokrakam** [comment]
Interesting use of `CS`, but I wonder if `find( )` is not easier to understand?
`DATA(lv_first_pos) = find( val = sy-abcde sub = student(1) ) * 2.`

**Comment by shafiq2601** [comment]
Wow. find( ) makes so much more sense here indeed.
Thanks for the suggestion.

I tried changing the code accordingly but ended with new error.

<img width="896" alt="image" src="https://user-images.githubusercontent.com/38856414/161561948-98fe8d9d-0d67-42f7-90ae-0853df677de5.png">

**Comment by shafiq2601** [comment]
Yes. Period (.) was missing and was causing syntax error in exercism editor.
I have fixed it and tested again but ended with following test failures.

<img width="939" alt="image" src="https://user-images.githubusercontent.com/38856414/161738264-556f1d32-4c62-439e-9f7c-6fd7c0c47726.png">

I copied the code to real SAP system and executed the tests. All tests were passed successfully.

**Comment by larshp** [comment]
https://github.com/abaplint/abaplint/pull/2493/commits/d8350545c4e3095a4df0527f31d237ff187e7f77

**Comment by larshp** [comment]
@shafiq2601 try again,

![image](https://user-images.githubusercontent.com/5888506/162609546-7a94995a-e033-403f-812d-a241a143e644.png)

**Comment by shafiq2601** [comment]
Thank you @larshp. I was able to submit the solution. Really appreciate how you are managing to take out time and attend to all these issues one by one. Respect ✊
