### ISSUE TITLE
Time out when running tests for RESISTOR_COLOR

### ISSUE THREAD

**Issue by BaerbelW** [exercism/abap#133]
I get a time out error when running the tests for RESISTOR_COLOR
![grafik](https://user-images.githubusercontent.com/18588108/162443342-7198c168-3ce7-4b29-b9db-aba8da794477.png)
And after about a minute I see this message:
"Your tests timed out. This might mean that there was an issue in our infrastructure, but more likely it suggests that your code is running slowly. Is there an infinite loop or something similar?"

My code is below and doesn't have a loop statement included and I was getting the time out even when running the tests before I added any code.

```abap
CLASS zcl_resistor_color DEFINITION PUBLIC CREATE PUBLIC.
  PUBLIC SECTION.
    METHODS resistor_color
      IMPORTING
        color_code   TYPE string
      RETURNING
        VALUE(value) TYPE i.

ENDCLASS.

CLASS zcl_resistor_color IMPLEMENTATION.

  METHOD resistor_color.
    case color_code.
      when 'black'.
        value = 0.
      when 'brown'.
        value = 1.
      when 'red'.
        value = 2.
      when 'orange'.
        value = 3.
      when 'yellow'.
        value = 4.
      when 'green'.
        value = 5.
      when 'blue'.
        value = 6.
      when 'violet'.
        value = 7.
      when 'grey'.
        value = 8.
      when 'white'.
        value = 9.
     endcase.
  ENDMETHOD.

ENDCLASS.
```

**Comment by larshp** [comment]
hmm, yea, I'm experiencing the same issue

**Comment by larshp** [comment]
running it locally works, running the CI tests works, https://github.com/exercism/abap/runs/5885902692?check_suite_focus=true

might be a generic Exercism issue

**Comment by larshp** [comment]
might be same issue as https://github.com/exercism/exercism/issues/6321

**Comment by larshp** [comment]
@BaerbelW try again, see https://github.com/exercism/exercism/issues/6321#issuecomment-1092939370

**Comment by BaerbelW** [comment]
@larshp - I just tried and it's working again as it should! Thanks
