### ISSUE TITLE
Prime Factors - The inline function frac( ) is not interpreted correctly

### ISSUE THREAD

**Issue by aferngas** [exercism/abap#135]
While developing the solution for the exercise, I noticed that when I used the frac( ) function, the result was not correct when extracting the decimal part of a decfloat34 variable.

Here is the first version of the full code I'm trying, which is not passing the unit testing on the platform:

```abap
CLASS zcl_prime_factors DEFINITION PUBLIC FINAL CREATE PUBLIC .
  PUBLIC SECTION.
    TYPES integertab TYPE STANDARD TABLE OF i WITH EMPTY KEY.
    METHODS factors
      IMPORTING
        input         TYPE int8
      RETURNING
        VALUE(result) TYPE integertab.

  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS zcl_prime_factors IMPLEMENTATION.
  METHOD factors.
    DATA(lv_number) = input.
    DATA(lv_factor) = 2.
    WHILE lv_number <> 1.
      DATA(lv_result) = CONV decfloat34( lv_number / lv_factor ).
      IF frac( CONV decfloat34( lv_number / lv_factor ) ) = 0.
        lv_number = lv_number / lv_factor.
        INSERT lv_factor INTO TABLE result.
        CONTINUE.
      ENDIF.
      lv_factor = lv_factor + 1.
    ENDWHILE.
  ENDMETHOD.
ENDCLASS.
```

If I replace the frac( ) line with a classic MOD, it works correctly.
```abap
*      IF frac( CONV decfloat34( lv_number / lv_factor ) ) = 0.
      IF lv_number MOD lv_factor = 0.
```

I have found that if I split the statement into two parts, frac() still fails:
```abap
*      IF frac( CONV decfloat34( lv_number / lv_factor ) ) = 0.
      DATA(lv_result) = CONV decfloat34( lv_number / lv_factor ).
      IF frac( lv_result ) = 0.
```

Either code variant passes the tests in a Netweaver 7.4 system.

**Comment by larshp** [comment]
thanks reproduced as

```abap
  DATA lv_result TYPE decfloat34.
  lv_result = 7 / 2.
  WRITE frac( lv_result ).
```

![image](https://user-images.githubusercontent.com/5888506/162664809-c9d7c23e-6f8a-43ed-b276-3959fb1e7068.png)

**Comment by larshp** [comment]
https://github.com/abaplint/transpiler/pull/705

**Comment by larshp** [comment]
![image](https://user-images.githubusercontent.com/5888506/162691309-303134bc-4da2-463a-b2ac-155c20b86fb2.png)

**Comment by larshp** [comment]
@aferngas try again,

![image](https://user-images.githubusercontent.com/5888506/162695228-1c3432c0-3a09-4863-9a20-27624ab9ec46.png)

**Comment by aferngas** [comment]
@larshp, It worked perfectly with:

```abap
IF frac( CONV decfloat34( lv_number / lv_factor ) ) = 0.
```

![image](https://user-images.githubusercontent.com/20236851/162802224-a850a2f5-374f-4e36-a7c1-3387bb379861.png)
