### ISSUE TITLE
Kindergarten Garden: Constructor Expression REDUCE with multiple FOR not working

### ISSUE THREAD

**Issue by Mirandium** [exercism/abap#140]
Hi everybody,

I'm working on making my Kindergarten Garden solution more flexible (in case the kindergarten allows more plants per kid per row or gets new windowsills and has more than two rows).

I set up a trial account with account.hana.ondemand.com to have an ABAP instance available. Unfortunately, I couldn't find out the NetWeaver or ABAP version used, because there is no SAP GUI available for me. Just an Eclipse/ADT connection.
There, I set up the kindergarten class including all test cases from the exercise. 
All tests pass. 

In exercism all tests fail with either:
```
TEST_GARDEN_SINGLE_STUDENT

TEST FAILURE

Expected table to contain '4' rows , got '1'
```
or:
```
TEST_GARDEN_THIRD_STUDENTS

TEST FAILURE

Some exception raised
```

Here is my source code:

```abap
CLASS zcl_kindergarten_garden DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    METHODS constructor.
    METHODS plants
      IMPORTING
        diagram        TYPE string
        student        TYPE string
      RETURNING
        VALUE(results) TYPE string_table.

  PROTECTED SECTION.
  PRIVATE SECTION.
    DATA students TYPE string_table.

    METHODS get_plant_name
      IMPORTING code              TYPE c
      RETURNING VALUE(plant_name) TYPE string.
    DATA gv_code TYPE c.
    DATA gv_students TYPE string_table.
    DATA gv_plant_amount TYPE i.
ENDCLASS.


CLASS zcl_kindergarten_garden IMPLEMENTATION.
 METHOD constructor.
    gv_students = VALUE #( ( |Alice| ) ( |Bob| ) ( |Charlie| ) ( |David| ) ( |Eve| ) ( |Fred| )
                    ( |Ginny| ) ( |Harriet| ) ( |Ileana| ) ( |Joseph| ) ( |Kincaid| ) ( |Larry| ) ).
    gv_plant_amount = 2.
  ENDMETHOD.

  METHOD get_plant_name.
    gv_code = code.
    TRANSLATE gv_code TO UPPER CASE.
    plant_name = SWITCH #( gv_code WHEN 'V' THEN 'violets'
                                WHEN 'R' THEN 'radishes'
                                WHEN 'C' THEN 'clover'
                                WHEN 'G' THEN 'grass'
                          ).
  ENDMETHOD.

  METHOD plants.
    SPLIT diagram AT '\n' INTO TABLE DATA(window_rows).
    DATA(offset) = ( line_index( gv_students[ table_line = student ] ) - 1 ) * 2.
    results = REDUCE string_table( INIT s = VALUE string_table( )
                                   FOR r IN window_rows
                                   FOR p = 0 WHILE p < gv_plant_amount
                                   NEXT s = VALUE string_table(
                                          BASE s
                                          ( get_plant_name( substring( val = r off = offset + p len = 1 ) ) )
                                  )
              ).

  ENDMETHOD.
ENDCLASS.
```

The documentation says multiple FOR expressions are possible: [REDUCE - Reduction Operator](https://help.sap.com/doc/abapdocu_752_index_htm/7.52/de-DE/abenconstructor_expression_reduce.htm)

To show where I changed things and for reference what already works: This is an older version, where kids could only have two plants per row. It passes all tests on exercism:
```abap
    results = REDUCE string_table( init s = VALUE string_table( )
                        for r in window_rows
                        next s = VALUE #(
                                          BASE s
                                          ( get_plant_name( substring( val = r off = offset len = 1 ) ) )
                                          ( get_plant_name( substring( val = r off = offset + 1 len = 1 ) ) )
                                        )
                      ).
```

I've got a wonderful mentor, who suggested to open an issue here. 
Hopefully, I managed to include all information needed to look into this issue. If something is missing, please let me know. I'll be happy to help.

Hopefully you can solve this issue.

Thank you all for the wonderful exercises to learn more about ABAP.

**Comment by larshp** [comment]
downport sequencing problem,

![image](https://user-images.githubusercontent.com/5888506/163564572-803be2d7-9555-4f0b-a88c-94cbfec39ae0.png)

**Comment by Mirandium** [comment]
Hi @larshp,

unfortunately I don't comprehend your answer. 
Does "downport sequencing problem" mean it's an issue with the transpiler? Or does it mean something different?

Is there any information I can provide to help?

**Comment by larshp** [comment]
closing
