### ISSUE TITLE
Atbash Cipher: 3 tests raise exception in exercism but pass in an sap system

### ISSUE THREAD

**Issue by Mirandium** [exercism/abap#142]
Hi everybody,

I'm working on the atbash cipher.

I set up a trial account with account.hana.ondemand.com to have an ABAP instance available. Unfortunately, I couldn't find out the NetWeaver or ABAP version used, because there is no SAP GUI available for me. Just an Eclipse/ADT connection.
There, I set up the atbash cipher class including all test cases from the exercise. 
All tests pass. 

In exercism the tests encode6, encode7 and encode8 fail. All three with the same message:
```
FAILED

Test 6

ENCODE6

TEST FAILURE

Some exception raised

```

Here is my source code:

```abap
CLASS zcl_atbash_cipher DEFINITION PUBLIC FINAL CREATE PUBLIC.

  PUBLIC SECTION.
    METHODS decode
      IMPORTING
        cipher_text TYPE string
      RETURNING
        VALUE(plain_text)  TYPE string .

METHODS encode
      IMPORTING
        plain_text        TYPE string
      RETURNING
        VALUE(cipher_text) TYPE string .

    METHODS constructor.
  PROTECTED SECTION.
  PRIVATE SECTION.
    Data plain type string.
    data cipher type string.
    METHODS translate
      IMPORTING
        original           TYPE string
      RETURNING
        VALUE(translation) TYPE string    .
ENDCLASS.



CLASS zcl_atbash_cipher IMPLEMENTATION.
  method constructor.
    plain  = |abcdefghijklmnopqrstuvwxyz0123456789|.
    cipher = |zyxwvutsrqponmlkjihgfedcba0123456789|.
  endmethod.

 METHOD decode.
    DATA(t) = cipher_text.
    CONDENSE t NO-GAPS.
    plain_text = translate( t ).
  ENDMETHOD.

  METHOD encode.
    DATA(plain_t) = replace( val = plain_text regex = '([[:punct:]])' with = ' ' occ = 0 ).
    CONDENSE plain_t NO-GAPS.
    plain_t = to_lower( plain_t ).
    DATA(cipher_string) = translate( plain_t ).
    cipher_text = condense( replace( val = cipher_string regex = '(.....)' with = `$1 ` occ = 0 ) ).
  ENDMETHOD.

  METHOD translate.
    translation = REDUCE string( INIT s TYPE string
                                  FOR r = 0 WHILE r < strlen( original )
                                  NEXT s = COND string(
                                    LET p = substring( val = original off = r len = 1 )
                                        l = find(  val = plain sub = p )
                                        c = substring( val = cipher off = l len = 1 )
                                        IN
                                        WHEN c NE '' THEN |{ s }{ c }|
                                        ELSE s
                                  )
        ).
  ENDMETHOD.
ENDCLASS.
```

I can make the tests on exercism pass as well, if I brute force them by adding the following lines of code to the method "encode". But that's no solution, in my humble opinion.
```abap
" special treatment for three testcases. The turn green in my abap environment but return "some exception raise" in exercism.org
" for test encode6
    if plain_text eq |Testing,1 2 3, testing.|.
      cipher_text = |gvhgr mt123 gvhgr mt|.
      exit.
" for test encode7
    elseif plain_text eq 'Truth is fiction.' .
      cipher_text = 'gifgs rhurx grlm'.
      exit.
" for test encode8
    elseif plain_text eq 'The quick brown fox jumps over the lazy dog.'.
      cipher_text = 'gsvjf rxpyi ldmul cqfnk hlevi gsvoz abwlt'.
      exit.
    endif.
```

Hopefully, I managed to include all information needed to look into this issue. If something is missing, please let me know. I'll be happy to help.

Hopefully you can solve this issue. I'd like to solve the exercise but can't get the tests to go green.

Thank you all for the wonderful exercises to learn more about ABAP.

**Comment by Dwivedirahul44** [comment]
There seems to be an issue with the built-in function **replace** handling abap character classes.
 after changing the code, all tests are passed.
![image](https://user-images.githubusercontent.com/43263062/164498416-19323442-68e9-4102-aa7e-feb00505bbe5.png)

**Comment by Dwivedirahul44** [comment]
An opened issue with abap lint:
[https://github.com/abaplint/transpiler/issues/716#issue-1211234496](URL)

**Comment by larshp** [comment]
https://github.com/abaplint/transpiler/issues/716

**Comment by larshp** [comment]
@Mirandium try again

![image](https://user-images.githubusercontent.com/5888506/166141811-c32baea1-01ec-4ae2-beba-f35f5a10d670.png)

**Comment by larshp** [comment]
closing
