### ISSUE TITLE
General issue "SCX_T100KEY not found" when running tests for ABAP exercises?

### ISSUE THREAD

**Issue by BaerbelW** [exercism/abap#143]
Regardless of which test I execute for a not yet tackled and therefore not changed ABAP exercise, I currently get the following error:
![grafik](https://user-images.githubusercontent.com/18588108/164686710-ccc2b54f-19dc-49c4-b82c-f98cfd16bb43.png)

This looks rather generic in nature.

Cheers
Bärbel

**Comment by larshp** [comment]
broken by https://github.com/exercism/abap-test-runner/pull/93#event-6476889905

to be fixed by https://github.com/exercism/abap-test-runner/pull/94

**Comment by larshp** [comment]
@BaerbelW try again

![image](https://user-images.githubusercontent.com/5888506/164709276-dfe01d31-634f-40d4-bc88-bef2583323a6.png)

**Comment by BaerbelW** [comment]
@larshp 
Thanks, Lars for the quick fix! It's working again.
