### ISSUE TITLE
Problem with number formatting in string template

### ISSUE THREAD

**Issue by 5311989** [exercism/abap#147]
Hello,
it seems that string template ignore embedded formatting for numbers.
When implementing my solution for the "Custom Signs" excercise, i get thre test failures (when testing method "cost_of")
because the price in the returned string was formatted without decimals.
I've tried for several ways, to make it happen.  See below my latest version with data type AND formatting instruction.
Both work pretty well on our Systen (NW 750).
Now it seems, i have to revert to WRITE TO FIELD :(

Edit: What i found out meanwhile is, that the built-in function conv doesn't work as expected and that seems to be another issue here. In my method "COST_OF" i have a self declared type of packed decimal with 2 decimal places. But converting an integer just produces an integer and not a converted P.2 value.

```abap
CLASS zcl_custom_signs DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC.

  PUBLIC SECTION.

    "! Build a sign that includes both of the parameters.
    METHODS build_sign IMPORTING occasion      TYPE string
                                 name          TYPE string
                       RETURNING VALUE(result) TYPE string.

    "! Build a birthday sign that conditionally formats the return string.
    METHODS build_birthday_sign IMPORTING age           TYPE i
                                RETURNING VALUE(result) TYPE string.

    "! Build a graduation sign that includes multiple lines
    METHODS graduation_for IMPORTING name          TYPE string
                                     year          TYPE i
                           RETURNING VALUE(result) TYPE string.

    "! Determine cost based on each character of sign parameter that builds
    "! the template string that includes the currency parameter.
    METHODS cost_of IMPORTING sign          TYPE string
                              currency      TYPE string
                    RETURNING VALUE(result) TYPE string.

ENDCLASS.



CLASS zcl_custom_signs IMPLEMENTATION.


  METHOD build_sign.
    "Implement solution here
    result = |Happy { occasion } { name }!|.
  ENDMETHOD.


  METHOD build_birthday_sign.
    "Implement solution here
    result = |Happy Birthday! What a { cond string( when age ge 50 then `mature` else `young` ) } fellow you are.|.
  ENDMETHOD.


  METHOD graduation_for.
    "Implement solution here
   result = |Congratulations { name }!\nClass of { year }|.
  ENDMETHOD.


  METHOD cost_of.
    "Implement solution here
    types lty_dec2 type p length 4 decimals 2.
    data(cost) = conv lty_dec2( strlen( sign ) * 2 + 20 ).
    result = |Your sign costs { cost currency = 'EUR' } { currency }.|.
  ENDMETHOD.


ENDCLASS.
```

**Comment by larshp** [comment]
suggest using `|Your sign costs { cost DECIMALS = 2 } { currency }.|` for this exercise

as of now, the transpiler does not know of currencies so I'll change it so it dumps

**Comment by larshp** [comment]
https://github.com/abaplint/transpiler/pull/721/commits/5bbe8c9b9b4c5582d3e63008aa64c893cb4bca4d

**Comment by 5311989** [comment]
Hi Lars,
workaround works, but there's still the issue with CONV ttt(...)
Probably I shold have opened another issue for that, but here's what i encountered:
Depending on the combination of explicit and implicit conversion, the outcome differs remarcably.
When i use an explicit conversion by built-in function conv, it is obviously ignored like in this example:
```
  METHOD cost_of.
    "Implement solution here
    types lty_dec2 type p decimals 2.
    data(cost) = conv lty_dec2( 20 + strlen( sign ) * 2 ).
    result = |Your sign costs { cost DECIMALS = 2  } { currency }.|.
  ENDMETHOD.
```
where the test returns failure with:
```
Expected 'Your sign costs 50.00 dollars.', got 'Your sign costs 50 dollars.'
```
So i tried a slightly different approach, forcing the data type of inline declared variable to my desired datatype.
Here's the code:
```
  METHOD cost_of.
    "Implement solution here
    types lty_dec2 type p decimals 2.
    data(cost) = conv lty_dec2( 20 ).
    cost = cost + strlen( sign ) * 2.
    result = |Your sign costs { cost DECIMALS = 2  } { currency }.|.
  ENDMETHOD.
```
And the result of the testrun:
``` 
Expected 'Your sign costs 50.00 dollars.', got 'Your sign costs 5,0000000000000000E+01 dollars.'
```
This time, CONV ttt( ) seems to resolve to float!?!?

But weirder and weirder it gets.
Converting the product of an integer and an already converted value, results in my complete irritation, as the outcome of the testrun suggests, that the reuslting value has been converted to float, but by factor ten too low:
```
  METHOD cost_of.
    "Implement solution here
    types lty_dec2 type p decimals 2.
    data(cost) = conv lty_dec2( 20 ).
    cost = cost + conv lty_dec2( strlen( sign )* conv lty_dec2( 2 ) ) .
    result = |Your sign costs { cost DECIMALS = 2  } { currency }.|.
  ENDMETHOD.
```
Testresult:
```
Expected 'Your sign costs 50.00 dollars.', got 'Your sign costs 2,3000000000000000E+01 dollars.'
```

**Comment by larshp** [comment]
another fix,
https://github.com/abaplint/transpiler/pull/736/commits/7ee099cc9021026f03bdafec4db13ccf3a508856

**Comment by 5311989** [comment]
@larshp 
Hi Lars,
wow, i really appreciate your hard work. 
Am i correct to assume, that your changes have not been integrated yet?
Because i still get those weird results.
```
  METHOD cost_of.
    "Implement solution here
*    types lty_dec2 type P decimals 2.
    data cost type p decimals 2.
    cost = 20 + strlen( sign ) * 2 .
    result = |Your sign costs { cost DECIMALS = 2  } { currency }.|. 
  ENDMETHOD.
```
results in
```
Expected 'Your sign costs 50.00 dollars.', got 'Your sign costs 50 dollars.'
```

**Comment by larshp** [comment]
yea, its still in https://github.com/abaplint/transpiler/pull/736, it must be merged, a new version published. And then https://github.com/exercism/abap-test-runner will be updated to use the new version

you can keep an eye on https://github.com/exercism/abap-test-runner for when the runner is updated :)

**Comment by larshp** [comment]
so far, so good, 

![image](https://user-images.githubusercontent.com/5888506/168252444-127259d8-af35-481a-b337-955c9a08d73e.png)

**Comment by larshp** [comment]
@5311989 try again, updated, I only looked into the first example, not the thing with the floating point number

**Comment by 5311989** [comment]
You guys rock. It's amazing to see the efford you put into it.
Now for your fix.
Yees, it does run correctly IF i stick to converting the result of a therm. like
```
types: lty_dec2 type P decimals 2.
data(cost) = conv lty_dec2( 20 + strlen( sign ) * 2  ).
```
But now implicit conversion runs into error. The following code should run fine. BUT:
```
  METHOD cost_of.
    "Implement solution here
    types lty_dec2 type P decimals 2.
    data(cost) = conv lty_dec2( 20 ).
    cost = cost + strlen( sign ) * 2 .
    result = |Your sign costs { cost decimals = 2  } { currency }.|.  
  ENDMETHOD.
```
receives errormessage:
```
We received the following error when we ran your code:
TypeError: source.get(...).toFixed is not a function
    at ABAP.templateFormatting (/usr/local/lib/node_modules/@abaplint/runtime/build/src/template_formatting.js:34:29)
    at zcl_custom_signs.cost_of (file:///tmp/exercism-abap-runner-Owx0oE/compiled/zcl_custom_signs.clas.mjs:55:68)
    at ltc_cost.character_count (file:///tmp/exercism-abap-runner-Owx0oE/compiled/zcl_custom_signs.clas.testclasses.mjs:75:88)
    at Function.run (file:///tmp/exercism-abap-runner-Owx0oE/compiled/kernel_unit_runner.clas.mjs:126:77)
    at async run (file:///tmp/exercism-abap-runner-Owx0oE/compiled/index_open.mjs:47:17)
```

**Comment by larshp** [comment]
thanks, another unit test to be added 😄

**Comment by larshp** [comment]
https://github.com/abaplint/transpiler/pull/737

**Comment by larshp** [comment]
@5311989 try again, runner updated

**Comment by 5311989** [comment]
Thanks, works like a charm now.

**Comment by larshp** [comment]
🥳
