### ISSUE TITLE
Add Concepts to the ABAP track

### ISSUE THREAD

**Issue by schmelto** [exercism/abap#150]
Is it applicable for the ABAP track to add some concepts like for in example the JavaScript track (see [here](https://exercism.org/tracks/javascript/concepts))?

The documentation on how to add concepts can be found [here](https://exercism.org/docs/building/tracks/concepts).

My idea for example the concept `basics` could be a short description what ABAP is what it is used for and maybe some specialties like that in ABAP the statement ends with `.` and not like in many other programming languages with `;`.

What are your thoughts on this one?

**Comment by larshp** [comment]
see https://github.com/exercism/abap/pull/87
