### ISSUE TITLE
Enable linting

### ISSUE THREAD

**Issue by mbtools** [exercism/abap#155]
We would like to enable linting of ABAP code in this repo. 

1. Sign-up "exercism" to abaplint at https://github.com/marketplace/abaplint
2. Go to pricing and pick "Public Repositories" (free) and "exercism" under account
![image](https://user-images.githubusercontent.com/59966492/170079076-8dcd076a-4bdf-41cc-a5f9-83ea292a39a7.png)
3. Go to "exercism" origanization settings "GitHub Apps" at https://github.com/organizations/exercism/settings/installations
4. Select "abaplint" and enable access to repository "exercism/abap"
![image](https://user-images.githubusercontent.com/59966492/170079690-1db4b992-38ed-4a81-b47a-c81d7ec1a064.png)

@ErikSchierboom, @iHiD would one of you be able to set this up, please?

PS: Initial linting rules are already setup (in abaplint.json). We will fine-tune them once we have the initial linting results.

**Comment by larshp** [comment]
I am the maintainer of the app on the marketplace...

**Comment by iHiD** [comment]
Done 🙂
