### ISSUE TITLE
abaplint job fails

### ISSUE THREAD

**Issue by mbtools** [exercism/abap#158]
The abaplint check is failing with "Error: Command failed: git checkout <commit>" and the job does not complete. 

Example:

- Check: https://github.com/exercism/abap/pull/157/checks?check_run_id=6653135122

![image](https://user-images.githubusercontent.com/59966492/170981506-fbf1afa9-608f-466b-a81d-a152612bc568.png)

- Error: https://abaplint.app/jobs (shows most recent jobs only)

![image](https://user-images.githubusercontent.com/59966492/170981460-56bda6e9-bb58-4929-9a3b-7ed8eee85d39.png)

@iHiD could you please check if the permissions are set properly for abaplint app and that `exercism/abap` is selected for repo access?

https://github.com/organizations/exercism/settings/installations > abaplint > configure

Any other idea why the checkout fails?

**Comment by mbtools** [comment]
It works sometimes (showing 72 issues), fails sometimes (git checkout error)... hmmm

![image](https://user-images.githubusercontent.com/59966492/171140721-8057b9b5-d04d-4aba-b0b5-5c0549d8dc32.png)

**Comment by larshp** [comment]
@mbtools fixed, closing
