### ISSUE TITLE
Binary Counter

### ISSUE THREAD

**Issue by stefanklos90** [exercism/abap#173]
A new exercise where you have to implement a binary counter. 
The object offers three methods, one to increment the counter, one to decrement the counter and one to get the current value of the counter.

**Comment by larshp** [comment]
hi,
we usually take new exercises from https://github.com/exercism/problem-specifications

but other exercises are also welcome 😄

**Comment by larshp** [comment]
@stefanklos90 is this something you intend to work on ?

**Comment by larshp** [comment]
closing, no reply
