### ISSUE TITLE
field-symbol in constructor expression not available

### ISSUE THREAD

**Issue by mem1b** [exercism/abap#182]
With the following Code i ran into this error:
![image](https://user-images.githubusercontent.com/1336470/189476691-ad88c0e5-4e24-4422-89d3-79c2db4f7ddb.png)
```
    combined_data = VALUE #(
      FOR <a> IN alphas INDEX INTO i
      LET n = nums[ i ] IN (
       colx = <a>-cola && n-col1
       coly = <a>-colb && n-col2
       colz = <a>-colc && n-col3
       ) ).
```
Locally on my 7.55 it's working & all tests passed:

![image](https://user-images.githubusercontent.com/1336470/189476836-b150fbfc-3e42-4bbb-9c3c-2f76b2227df3.png)

**Comment by larshp** [comment]
https://github.com/abaplint/abaplint/pull/2677/commits/a2583a82c479429d6948e6daba5c01c41c58d229

**Comment by larshp** [comment]
@mem1b try again, everything updated

**Comment by mem1b** [comment]
works, thanks!
