### ISSUE TITLE
"index into" not available in for-constructor expression

### ISSUE THREAD

**Issue by mem1b** [exercism/abap#183]
With the following Code i ran into this error:
![image](https://user-images.githubusercontent.com/1336470/189476745-668379d7-7876-4b0a-a39e-56c68cafe487.png)

```
    combined_data = VALUE #(
      FOR a IN alphas INDEX INTO i
      LET n = nums[ i ] IN (
       colx = a-cola && n-col1
       coly = a-colb && n-col2
       colz = a-colc && n-col3
       ) ).
```
Locally on my 7.55 it's working & all tests passed:
![image](https://user-images.githubusercontent.com/1336470/189476800-6de45afa-22af-4642-9e70-bdbc1cbc52e7.png)

**Comment by larshp** [comment]
reproduced as

```abap
TYPES inttab TYPE STANDARD TABLE OF i WITH DEFAULT KEY.
DATA alphas TYPE inttab.
DATA lv_index TYPE i.

APPEND 2 TO alphas.
APPEND 2 TO alphas.

DATA(indexes) = VALUE inttab(
  FOR a IN alphas INDEX INTO i
  ( i ) ).

LOOP AT indexes INTO lv_index.
  WRITE / lv_index.
ENDLOOP.
```

**Comment by larshp** [comment]
https://github.com/abaplint/abaplint/pull/2677/commits/ea45a8711c6b993202cb9b6047f6347e170c68d4

**Comment by larshp** [comment]
@mem1b try again, everything updated

**Comment by mem1b** [comment]
works, thanks!
