### ISSUE TITLE
Week2 : ABAP Challenge: ITAB combination

### ISSUE THREAD

**Issue by malikvikram16** [exercism/abap#187]
I used below 2 methods in SAP DEV environment and its working fine. But in Excercism, it's giving me error
"Way2
"=======
 ""  combined_data[] = alphas[].
 ""  loop at combined_data assigning field-symbol(<fs_comb>).
 ""      data(lv_index) = sy-tabix.
 ""     <fs_comb>-colx = |{ <fs_comb>-colx }{ nums[ lv_index ]-col1 }|.
 ""     <fs_comb>-coly = |{ <fs_comb>-coly }{ nums[ lv_index ]-col2 }|.
   ""   <fs_comb>-colz = |{ <fs_comb>-colz }{ nums[ lv_index ]-col3 }|.
 ""  endloop.

"Way3
"====
  "" combined_data  =  value combined_data( 
    ""                   for ls_alpha in alphas index into lv_index 
    ""               for ls_num in nums from lv_index to lv_index
  ""                  let ls_comb = value combined_data_type( 
""                      colx = |{ ls_alpha-cola }| & |{ ls_num-col1 }|
  ""                        coly = |{ ls_alpha-colb }| & |{ ls_num-col2 }|
  ""                        colz = |{ ls_alpha-colc }| & |{ ls_num-col3 }| )
  ""                    IN ( corresponding #( ls_comb  ) )

**Comment by larshp** [comment]
the exercise is https://exercism.org/tracks/abap/exercises/itab-combination

**Comment by larshp** [comment]
way3, 

```abap
    combined_data = VALUE combined_data(
      FOR ls_alpha IN alphas INDEX INTO lv_index
      FOR ls_num IN nums FROM lv_index TO lv_index
      LET ls_comb = VALUE combined_data_type(
      colx = |{ ls_alpha-cola }| & |{ ls_num-col1 }|
      coly = |{ ls_alpha-colb }| & |{ ls_num-col2 }|
      colz = |{ ls_alpha-colc }| & |{ ls_num-col3 }| )
      IN ( CORRESPONDING #( ls_comb ) ) ).
```

**Comment by larshp** [comment]
@malikvikram16 try again, everything updated

![image](https://user-images.githubusercontent.com/5888506/190859484-0599519a-3ecd-4346-9921-8c571a14b99e.png)

![image](https://user-images.githubusercontent.com/5888506/190859504-622eff2b-6624-4fb9-a54d-c2ccd77f64a0.png)

**Comment by malikvikram16** [comment]
Hello Lars,
What was the issue  with Way 3  and Way 4. looks like th issue was due to some another bug ( https://github.com/abaplint/transpiler/pull/877 ).
Can you please explain in few lines why  both ways were not working.

Regards,
Vikram Singh

**Comment by larshp** [comment]
way 2: moving structures with different field names did not work properly in the runtime, fixed in https://github.com/abaplint/transpiler/pull/877

way 3: downport of CORRESPONDING did not work in abaplint, plus some syntax checking errors in relation to FOR scopes, fixed in https://github.com/abaplint/abaplint/pull/2686

**Comment by larshp** [comment]
@malikvikram16 did above help? can we close the issue?

**Comment by malikvikram16** [comment]
Please close it.

Thanks!
