### ISSUE TITLE
Creating private Method doesn't work

### ISSUE THREAD

**Issue by GirodFred** [exercism/abap#188]
Hi team, I have another issu, this time with Scrabble-Score,

It seems the METHODS statement is not recognized. 

The whole code : 
```
CLASS zcl_scrabble_score DEFINITION PUBLIC .

  PUBLIC SECTION.
    METHODS score
      IMPORTING
        input         TYPE string OPTIONAL
      RETURNING
        VALUE(result) TYPE i.
  PROTECTED SECTION.
  PRIVATE SECTION.
    methods get_value_for_letter
      importing
        input type char length 1
      returning
         value(result) type n.

ENDCLASS.


CLASS zcl_scrabble_score IMPLEMENTATION.
  METHOD score.
    " add solution here
    data(word_length) = strlen( input ).
    do word_length times.
      result = result + get_value_for_letter( substring( val = input  off = sy-index  len = 1 ) ).
    enddo.
  ENDMETHOD.


  METHOD get_value_for_letter.
    result = SWITCH #(
               input
               WHEN 'A' OR 'E' OR 'I' OR 'O' OR 'U' OR 'L' OR 'N' OR 'R' OR 'S' OR 'T'
                 THEN 1
               WHEN 'D' OR 'G'
                 THEN 2
               WHEN 'B' OR 'C' OR 'M' OR 'P'
                 THEN 3
               WHEN 'F' OR 'H' OR 'V' OR 'W' OR 'Y'
                 THEN 4
               WHEN 'K'
                 THEN 5
               WHEN 'J' OR 'X'
                 THEN 8
               WHEN 'Q' OR 'Z'
                 THEN 10  ).
  ENDMETHOD.


ENDCLASS.

```

The error : 

``
We received the following error when we ran your code:
./zcl_scrabble_score.clas.abap[11, 5] - Statement does not exist in ABAPopen-abap(or a parser error), "methods" (parser_error) [E]
./zcl_scrabble_score.clas.abap[26, 7] - Method "get_value_for_letter" not found, methodCallChain (check_syntax) [E]
./zcl_scrabble_score.clas.abap[31, 3] - Method definition "get_value_for_letter" not found (check_syntax) [E]
abaplint: 3 issue(s) found
``

**Comment by larshp** [comment]
Hi,
in ABAP its not possible to define LEGNTH in a METHODS statement

must do something like

```abap
CLASS lcl DEFINITION.
  PRIVATE SECTION.
    TYPES ty TYPE c LENGTH 1.
    METHODS get_value_for_letter
      IMPORTING
        input         TYPE ty.
ENDCLASS.
```

![image](https://user-images.githubusercontent.com/5888506/190956359-54770bf0-68df-4350-a890-edbc4a2943d4.png)

**Comment by GirodFred** [comment]
@larshp  well done!   I don't recopy the Class Definition between Eclipse & Exercism

**Comment by GirodFred** [comment]
@larshp  I am not agree with lowercase test. It is not specified to be not case sensitive

**Comment by larshp** [comment]
consider "methods" a help to the developer to identify which line has an error

**Comment by larshp** [comment]
@GirodFred did above help? can we close the issue?

it is a syntax error and reported as a syntax error

**Comment by GirodFred** [comment]
Yes we can
I thought I already did it 


Fred

Envoyé de mon iPhone
