### ISSUE TITLE
ITAB Aggregation: LOOP AT GROUP issue

### ISSUE THREAD

**Issue by bigld** [exercism/abap#190]
Exercise https://exercism.org/tracks/abap/exercises/itab-aggregation

`    LOOP AT initial_numbers ASSIGNING FIELD-SYMBOL(<number>)
                            GROUP BY ( group = <number>-group
                                       count = GROUP SIZE )
                            ASSIGNING FIELD-SYMBOL(<groups>).

      LOOP AT GROUP <groups> ASSIGNING FIELD-SYMBOL(<group>).

      ENDLOOP.
    ENDLOOP.`

![image](https://user-images.githubusercontent.com/4643389/191018419-a62bc66e-f81e-4025-811e-f882d72d00f1.png)

**Comment by larshp** [comment]
as temporary workaround: some of the variants with LOOP GROUP INTO instead of ASSIGNING might work

**Comment by bigld** [comment]
better but still not working :(

`    LOOP AT initial_numbers INTO DATA(number)
                            GROUP BY number-group 
                            INTO DATA(groups).

      LOOP AT GROUP groups INTO DATA(group).

      ENDLOOP.
    ENDLOOP.`


Errors
./zcl_itab_aggregation.clas.abap[46, 1] - Statement does not exist in ABAPopen-abap(or a parser error), "READ" (parser_error) [E]
./zcl_itab_aggregation.clas.abap[48, 3] - "<temp2>" not found, Target (check_syntax) [E]
./zcl_itab_aggregation.clas.abap[58, 7] - Not a object reference, field chain (check_syntax) [E]
./zcl_itab_aggregation.clas.abap[59, 7] - "group" not found, Target (check_syntax) [E]

**Comment by larshp** [comment]
https://github.com/abaplint/abaplint/pull/2690

**Comment by larshp** [comment]
@bigld try again, it should now cover INTO, REFERENCE INTO, ASSIGNING

**Comment by bigld** [comment]
This works now, thanks!
