### ISSUE TITLE
ITAB Aggregation issues

### ISSUE THREAD

**Issue by A142612** [exercism/abap#191]
I have the issue with ITAB Aggregation as well. I provided two solutions, one with  loop group by, the other without loop group by. The one with loop..group by could not pass syntax check. the one without loop..group by cant pass the unit test. But both solutions passed abap unit test successfully in SAP BTP abap environment. 
![abaperror](https://user-images.githubusercontent.com/46800633/191251478-8db57489-0784-4659-801b-7f944db37171.PNG)
![abapseccu](https://user-images.githubusercontent.com/46800633/191251575-af6dd7fe-f4d1-4353-bd37-135965a0abf8.PNG)

**Comment by larshp** [comment]
thanks, can you help pasting the code here as text, so I can copy paste it to test?

**Comment by A142612** [comment]
METHOD perform_aggregation.
    " add solution here
     DATA icount TYPE i.
    TYPES: BEGIN OF group_type,
             group TYPE group,
             size  TYPE i,
           END OF group_type,
           group_types TYPE STANDARD TABLE OF group_type WITH EMPTY KEY.
    DATA temp_numbers TYPE initial_numbers.
    temp_numbers[] =  initial_numbers[].
    SORT temp_numbers BY group ASCENDING.
    DATA last_group TYPE c.
    DATA group_numbers TYPE group_types.
    LOOP AT temp_numbers INTO DATA(initial_number).
      IF last_group <> initial_number-group.
        APPEND INITIAL LINE TO group_numbers  ASSIGNING FIELD-SYMBOL(<group_number>).
        <group_number>-group = initial_number-group.
        <group_number>-size = 1.
      ELSE.
        <group_number>-size += 1.
      ENDIF.
      last_group =  initial_number-group.
    ENDLOOP.

    LOOP AT group_numbers INTO DATA(group_number).
      APPEND INITIAL LINE TO aggregated_data ASSIGNING FIELD-SYMBOL(<aggregated_data>).
      <aggregated_data>-group =  group_number-group.
      <aggregated_data>-count = group_number-size.
      icount = 0.
      LOOP AT temp_numbers INTO DATA(ls_member) WHERE group =  group_number-group.
        <aggregated_data>-sum  += ls_member-number.
        IF icount = 0.
          <aggregated_data>-min = <aggregated_data>-max = ls_member-number.
        ELSE.
          <aggregated_data>-min =  COND i( WHEN ls_member-number < <aggregated_data>-min THEN ls_member-number ELSE <aggregated_data>-min ).
          <aggregated_data>-max =  COND i( WHEN ls_member-number > <aggregated_data>-max THEN ls_member-number ELSE <aggregated_data>-max ).
        ENDIF.
        icount += 1.
      ENDLOOP.
      <aggregated_data>-average = <aggregated_data>-sum /  <aggregated_data>-count.
    ENDLOOP.
  ENDMETHOD.

**Comment by A142612** [comment]
METHOD perform_aggregation.
    " add solution here

    LOOP AT initial_numbers INTO DATA(initial_number)
      GROUP BY ( group  = initial_number-group
                 size  = GROUP SIZE
                 index = GROUP INDEX )
      ASCENDING
      ASSIGNING FIELD-SYMBOL(<group>).

      APPEND INITIAL LINE TO aggregated_data ASSIGNING FIELD-SYMBOL(<aggregated_data>).

      <aggregated_data>-group =  <group>-group. "initial_number-group. <>
      <aggregated_data>-count = <group>-size.
      DATA(icount) = 0.

      LOOP AT GROUP <group> ASSIGNING FIELD-SYMBOL(<ls_member>).
        <aggregated_data>-sum  += <ls_member>-number.
        IF icount = 0.
          <aggregated_data>-min = <aggregated_data>-max = <ls_member>-number.

        ELSE.
          <aggregated_data>-min =  COND i( WHEN <ls_member>-number < <aggregated_data>-min THEN <ls_member>-number ELSE <aggregated_data>-min ).
          <aggregated_data>-max =  COND i( WHEN <ls_member>-number > <aggregated_data>-max THEN <ls_member>-number ELSE <aggregated_data>-max ).
        ENDIF.

        icount += 1.
      ENDLOOP.
      <aggregated_data>-average = <aggregated_data>-sum /  <aggregated_data>-count.
    ENDLOOP.
  ENDMETHOD.

**Comment by larshp** [comment]
@A142612 for the first case,

the workaround is not having `<aggregated_data>-min = <aggregated_data>-max = ls_member-number.`

also note it is considered bad practice to use chained assignment, https://github.com/SAP/styleguides/blob/main/clean-abap/CleanABAP.md#dont-chain-assignments

![image](https://user-images.githubusercontent.com/5888506/191254603-3141b98f-dda3-4e5e-a39e-5d50fdf75e00.png)

**Comment by larshp** [comment]
enabling no_chained_assignment rule = https://github.com/abaplint/transpiler/pull/881

**Comment by larshp** [comment]
second LOOP GROUP BY, some bugs in https://syntax.abaplint.org/?filter=groupby#/abap/expression/LoopGroupByComponent

wip, https://github.com/abaplint/abaplint/pull/2691

**Comment by larshp** [comment]
second, workaround,

refactor the chained assignment

and remove "index = GROUP INDEX", as it is not used in the code,

![image](https://user-images.githubusercontent.com/5888506/191257417-c23a8286-13a2-4283-9abb-41e2ac557ee1.png)

**Comment by larshp** [comment]
now gives proper error message for chained assignment,

![image](https://user-images.githubusercontent.com/5888506/191268150-5631eb76-3c5f-4850-bd58-9ac700f44d0f.png)

**Comment by larshp** [comment]
@A142612 try again

**Comment by AndreaBorgia-Abo** [comment]
Came here looking to understand why this does not work:
```
        aggregated_data[ group = <fs_ini_numbers>-group ]-max = COND #( 
          when <fs_ini_numbers>-number > aggregated_data[ group = <fs_ini_numbers>-group ]-max 
          then <fs_ini_numbers>-number
          else aggregated_data[ group = <fs_ini_numbers>-group ]-max
          ).
```
and got the inspiration to try an explicit type, which solved the problem. Sadly at the moment I don't have a system supporting the new syntax, but I thought the code above was valid, am I mistaken?

**Comment by larshp** [comment]
@AndreaBorgia-Abo please open a new issue, I consider this issue solved

**Comment by larshp** [comment]
@A142612 try again

**Comment by larshp** [comment]
FYI, chained assignment will work in next release, https://github.com/abaplint/transpiler/pull/887/commits/53e090c3af74346a22d1cd226d88e9684a91b84d

**Comment by larshp** [comment]
with chained assignment,
![image](https://user-images.githubusercontent.com/5888506/192137450-fb1346d0-efa1-44b8-a7e2-1d06d77f229d.png)

**Comment by larshp** [comment]
closing
