### ISSUE TITLE
Custom Signs Issue

### ISSUE THREAD

**Issue by berinath3** [exercism/abap#192]
I wrote code for Custom Signs and it was executed in my local systems. But it was not executed on exercism. Please help me in that.

I am getting error .
<img width="322" alt="error" src="https://user-images.githubusercontent.com/54433105/191256529-d9ae1243-d0a6-4013-8d81-68848456751f.png">

Thanks,
Berinath Ulisi.

**Comment by larshp** [comment]
@berinath3 thanks, can you help by pasting the code here as text, so it can be used for reproducing?

**Comment by larshp** [comment]
hmm, looks like it can be reproduced with the empty implementation, 

![image](https://user-images.githubusercontent.com/5888506/191258759-eafea540-1fac-455b-a476-5e49f5ae6955.png)

**Comment by larshp** [comment]
json escaping error,

![image](https://user-images.githubusercontent.com/5888506/191260793-e69f79e6-1a13-4381-abe3-7174c83e8d52.png)

**Comment by berinath3** [comment]
CLASS zcl_custom_signs DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC.

  PUBLIC SECTION.

    "! Build a sign that includes both of the parameters.
    METHODS build_sign IMPORTING occasion      TYPE string
                                 name          TYPE string
                       RETURNING VALUE(result) TYPE string.

    "! Build a birthday sign that conditionally formats the return string.
    METHODS build_birthday_sign IMPORTING age           TYPE i
                                RETURNING VALUE(result) TYPE string.

    "! Build a graduation sign that includes multiple lines
    METHODS graduation_for IMPORTING name          TYPE string
                                     year          TYPE i
                           RETURNING VALUE(result) TYPE string.

    "! Determine cost based on each character of sign parameter that builds
    "! the template string that includes the currency parameter.
    METHODS cost_of IMPORTING sign          TYPE string
                              currency      TYPE string
                    RETURNING VALUE(result) TYPE string.

ENDCLASS.



CLASS zcl_custom_signs IMPLEMENTATION.


  METHOD build_sign.
    "Implement solution here
result = |Happy { occasion } { name }!|.
  ENDMETHOD.


  METHOD build_birthday_sign.
    "Implement solution here
if age >= 50.
result = |Happy Birthday! What a mature fellow you are.|.
else.
result = |Happy Birthday! What a young fellow you are.|.
endif.
  ENDMETHOD.


  METHOD graduation_for.
    "Implement solution here
result = |Congratulations { name }!\nClass of { year }|.
  ENDMETHOD.


  METHOD cost_of.
    "Implement solution here
result = |Your { sign } costs 58.00 { currency }.|.
  ENDMETHOD. 


ENDCLASS.

**Comment by berinath3** [comment]
But it is working on my local system
<img width="547" alt="error 1" src="https://user-images.githubusercontent.com/54433105/191263954-b39f71d3-bd37-4ea8-8348-e44c86df5e23.png">

**Comment by larshp** [comment]
@berinath3 try again, it should now give proper error messages,

![image](https://user-images.githubusercontent.com/5888506/191267782-2297656e-5741-4c82-849c-b2bf45da3546.png)

**Comment by berinath3** [comment]
Ok Thank you.
