### ISSUE TITLE
General issue of abaplint with FOR...IN... ? Scrabble Score

### ISSUE THREAD

**Issue by mickrig** [exercism/abap#195]
It seems there is a general issue using FOR...IN... maybe only in combination with REDUCE. 
Can you please check the issue?  
![2022-09-22 07_38_32-Exercism_Scrabble Score](https://user-images.githubusercontent.com/38348938/191896445-51571292-588b-4853-9344-c19e0cdb50da.png)

In my local environment the code works well.

```abap
    DATA letter TYPE c.
    DATA offset TYPE i.
    DATA char_tab TYPE STANDARD TABLE OF c WITH EMPTY KEY.

    DO.
      TRY.
          letter = substring( val = input
                              off = offset
                              len = 1 ).
          offset += 1.
          APPEND to_upper( letter ) TO char_tab.

        CATCH cx_sy_range_out_of_bounds.
          EXIT.
      ENDTRY.
    ENDDO.

    result = REDUCE i(
      INIT score TYPE i
      FOR char IN char_tab
      NEXT score = score + COND #(
                     WHEN matches( val = char pcre = `[AEIOULNRST]` )
                       THEN 1
                     WHEN matches( val = char pcre = `[DG]` )
                       THEN 2
                     WHEN matches( val = char pcre = `[BCMP]` )
                       THEN 3
                     WHEN matches( val = char pcre = `[FHVWY]` )
                       THEN 4
                     WHEN matches( val = char pcre = `[K]` )
                       THEN 5
                     WHEN matches( val = char pcre = `[JX]` )
                       THEN 8
                     WHEN matches( val = char pcre = `[QZ]` )
                       THEN 10 ) ).
```

**Comment by larshp** [comment]
thanks

at first sight I think its an issue with "pcre", try using old style "regex" instead in `matches`

https://github.com/abaplint/transpiler/blob/main/packages/runtime/src/builtin/matches.ts
https://github.com/abaplint/transpiler/blob/main/test/builtin/matches.ts

**Comment by mickrig** [comment]
Hi Lars, thanks for your feedback. But as you can see on the screenshot I provided there is no issue regarding matches. 
I got the same error without using matches in my ![other reported issue](https://github.com/exercism/abap/issues/194).

**Comment by larshp** [comment]
okay rename variable "char" to something else, it is a reserved keyword in JavaScript, which is the runtime. In the future it will automatically workaround this restriction

**Comment by larshp** [comment]
I dont see the screenshot, here is a screenshot of the broken screenshot,
![image](https://user-images.githubusercontent.com/5888506/191672113-3d779fc2-50ca-4d3f-a7b7-98431fc0d1f2.png)

**Comment by larshp** [comment]
after renaming,

![image](https://user-images.githubusercontent.com/5888506/191701060-d07b25d7-8f39-4778-a473-4dc75289e099.png)


```abap
  METHOD score.
    DATA letter TYPE c.
    DATA offset TYPE i.
    DATA char_tab TYPE STANDARD TABLE OF c WITH EMPTY KEY.

    DO.
      TRY.
          letter = substring( val = input
                              off = offset
                              len = 1 ).
          offset += 1.
          APPEND to_upper( letter ) TO char_tab.

        CATCH cx_sy_range_out_of_bounds.
          EXIT.
      ENDTRY.
    ENDDO.

    result = REDUCE i(
      INIT score TYPE i
      FOR foo IN char_tab
      NEXT score = score + COND #(
                     WHEN matches( val = foo pcre = `[AEIOULNRST]` )
                       THEN 1
                     WHEN matches( val = foo pcre = `[DG]` )
                       THEN 2
                     WHEN matches( val = foo pcre = `[BCMP]` )
                       THEN 3
                     WHEN matches( val = foo pcre = `[FHVWY]` )
                       THEN 4
                     WHEN matches( val = foo pcre = `[K]` )
                       THEN 5
                     WHEN matches( val = foo pcre = `[JX]` )
                       THEN 8
                     WHEN matches( val = foo pcre = `[QZ]` )
                       THEN 10 ) ).
  ENDMETHOD.
```

**Comment by larshp** [comment]
https://github.com/abaplint/transpiler/pull/883

**Comment by larshp** [comment]
now better error message,
![image](https://user-images.githubusercontent.com/5888506/191719255-123cffb5-272b-4180-bc2e-b84a9d6bae86.png)

**Comment by larshp** [comment]
and using regex,
![image](https://user-images.githubusercontent.com/5888506/191719332-9494de77-d6b0-407c-a6dc-8e60c1940640.png)

**Comment by larshp** [comment]
try again

its not perfect, but better. Helping with fixes is welcome. 

Currently I'm trying to not have totally misleading error messages, and getting code run with correct results

**Comment by mickrig** [comment]
Thanks Lars, with the provided corrections the code works now on exercism. Thanks.
