### ISSUE TITLE
itab aggregation error

### ISSUE THREAD

**Issue by thomasvillarubias** [exercism/abap#196]
Hi,

Related to this exercise – https://exercism.org/tracks/abap/exercises/itab-aggregation/

I tried below solution:
```
method perform_aggregation.
  loop at initial_numbers reference into data(initial_number).
    try.
        data(aggregated) = ref #( aggregated_data[ group = initial_number->group ] ).

      catch cx_sy_itab_line_not_found.
        insert initial line into table aggregated_data reference into aggregated.
        aggregated->group = initial_number->group.
        aggregated->min = initial_number->number.
        aggregated->max = initial_number->number.
        aggregated->average = initial_number->number.
    endtry.

    aggregated->count = aggregated->count + 1.
    aggregated->sum = aggregated->sum + initial_number->number.
    aggregated->min = cond #( when initial_number->number < aggregated->min
                                then initial_number->number
                              else aggregated->min ).

    aggregated->max = cond #( when initial_number->number > aggregated->max
                                then initial_number->number
                              else aggregated->max ).
    aggregated->average = aggregated->average + ( initial_number->number - aggregated->average ) / aggregated->count.

    clear aggregated.
  endloop.
endmethod.
```

Working well on SAP_ABA 750 (SP 19) but I receive errors on Exercism:
`./zcl_itab_aggregation.clas.abap[44, 7] - Variable name "temp1" already defined (check_syntax) [E]
./zcl_itab_aggregation.clas.abap[45, 7] - Variable name "temp2" already defined (check_syntax) [E]
./zcl_itab_aggregation.clas.abap[79, 9] - Incompatible types (check_syntax) [E]
./zcl_itab_aggregation.clas.abap[81, 9] - Incompatible types (check_syntax) [E]
abaplint: 4 issue(s) found`

When I explicitly declare the AGGREGATED variable (because that's the line pointed on line 44 from the above error messages) I get the following:
`TypeError: Cannot read properties of undefined (reading 'group')
    at zcl_itab_aggregation.perform_aggregation (file:///tmp/exercism-abap-runner-6qKayl/compiled/zcl_itab_aggregation.clas.mjs:36:27)
    at async ltcl_itab_aggregation.one_row (file:///tmp/exercism-abap-runner-6qKayl/compiled/zcl_itab_aggregation.clas.testclasses.mjs:59:68)
    at async Function.run (file:///tmp/exercism-abap-runner-6qKayl/compiled/kernel_unit_runner.clas.mjs:133:11)
    at async run (file:///tmp/exercism-abap-runner-6qKayl/compiled/_unit_open.mjs:53:17)`

**Comment by larshp** [comment]
one step of getting it working, https://github.com/abaplint/transpiler/pull/883/commits/31bdabdc6073f05c8bc7f73fb43f67b0b207fc4d

**Comment by larshp** [comment]
there are some floating point problems with your solution,

![image](https://user-images.githubusercontent.com/5888506/191757739-6dfa29a0-b2a9-41b8-9eda-bd4667dde5f7.png)

**Comment by larshp** [comment]
@thomasvillarubias try again,

![image](https://user-images.githubusercontent.com/5888506/191759980-fdb57ec7-2127-4116-b1d7-3cc7adb82f65.png)

**Comment by thomasvillarubias** [comment]
Hi @larshp ,

Thank you. I just retried and I have another error with the solution (I think it may be related to the floating point issue).
But I still share the error here because it is not very clear:
`Expected '[object Object]', got '[object Object]'`

It happens in the "Test 5 NEGATIVE" of the my first version of the algorithm.

**Comment by larshp** [comment]
=> see https://github.com/exercism/abap/issues/197, I'm fixing it in https://github.com/open-abap/open-abap/pull/461, will merge it in a few minutes and push a new exercism runner

**Comment by larshp** [comment]
@thomasvillarubias try again

**Comment by thomasvillarubias** [comment]
@larshp this is now working fine, I receive an expected failure on the negative test, with a legible error message.
Thanks for the work!
