### ISSUE TITLE
Scrabble Score - count_any_of is unknown

### ISSUE THREAD

**Issue by JSB-Vienna** [exercism/abap#204]
Hi, 
I tried to solve this exercise with this code:

```
  METHOD score.
    DATA(word) = to_upper( input ).
    result  = ( count_any_of( val = word  sub = `AEIOULNRST` ) * 1 ).
    result += ( count_any_of( val = word  sub = `DG`         ) * 2 ).
    result += ( count_any_of( val = word  sub = `BCMP`       ) * 3 ).
    result += ( count_any_of( val = word  sub = `FHVWY`      ) * 4 ).
    result += ( count_any_of( val = word  sub = `K`          ) * 5 ).
    result += ( count_any_of( val = word  sub = `JX`         ) * 8 ).
    result += ( count_any_of( val = word  sub = `QZ`         ) * 10 ).
  ENDMETHOD.

```
But I got the following error:  "TypeError: abap.builtin.count_any_of is not a function.

This runs smoothly on a 7.55 SP01.

**Comment by larshp** [comment]
thanks, its missing in the runtime, https://github.com/abaplint/transpiler/tree/main/packages/runtime/src/builtin

**Comment by larshp** [comment]
https://github.com/abaplint/transpiler/pull/888

**Comment by larshp** [comment]
@JSB-Vienna try again

![image](https://user-images.githubusercontent.com/5888506/192325217-ce84bc5e-2f5e-47b8-81b6-5b71fc2750f9.png)

**Comment by JSB-Vienna** [comment]
@larshp  Thank you very much for very quick response and solution. It works fine now.
