### ISSUE TITLE
Problem with Loop at .. group by  with multiple key components

### ISSUE THREAD

**Issue by TMNielsenApS** [exercism/abap#205]
I get some error I can't interpret when I use multiple key components in the GROUP BY by clause. The code works fine in "my own" SAP system.

Like this error:
```
       LOOP AT songs ASSIGNING FIELD-SYMBOL(<songs>)
                   GROUP BY ( artist = <songs>-artist_id
                                       album = <songs>-album_id )
                  ASCENDING ASSIGNING FIELD-SYMBOL(<group>).

      ENDLOOP.
```

Like this NO error:
 ```
   LOOP AT songs ASSIGNING FIELD-SYMBOL(<songs>)
                   GROUP BY ( artist = <songs>-artist_id )
                  ASCENDING ASSIGNING FIELD-SYMBOL(<group>).

    ENDLOOP.
```

**Comment by larshp** [comment]
hej hej, 🇩🇰 

the exercise is https://exercism.org/tracks/abap/exercises/itab-nesting

**Comment by larshp** [comment]
first fix = https://github.com/abaplint/abaplint/pull/2705

**Comment by larshp** [comment]
@TMNielsenApS try again

![image](https://user-images.githubusercontent.com/5888506/192441093-62fff759-1068-436c-bebb-084e00cd7ff2.png)

**Comment by TMNielsenApS** [comment]
Yes, thank you - it works now ...

... and now I realize that I don't need it for this exercise :-) 

PS. it very impressive how fast you fix issues - good work.
