### ISSUE TITLE
ITAB Nesting - Exercism TypeError: _c.get is not a function..

### ISSUE THREAD

**Issue by crazyhenk78** [exercism/abap#208]
Hi,

Both of my resolutions (both working fine in ABAP on premise) for the  ITAB Nesting challenge raise below error in Exercism:
`TypeError: _c.get is not a function
    at FieldSymbol.get (/usr/local/lib/node_modules/@abaplint/runtime/build/src/types/field_symbol.js:54:80)
    at ABAP.templateFormatting (/usr/local/lib/node_modules/@abaplint/runtime/build/src/template_formatting.js:11:23)
    at Function.dump_structure (file:///tmp/exercism-abap-runner-gYJKhk/compiled/cl_abap_unit_assert.clas.locals.mjs:48:169)
    at async Function.to_string (file:///tmp/exercism-abap-runner-gYJKhk/compiled/cl_abap_unit_assert.clas.locals.mjs:24:19)
    at async Function.assert_equals (file:///tmp/exercism-abap-runner-gYJKhk/compiled/cl_abap_unit_assert.clas.mjs:231:19)
    at async Function.assert_equals (file:///tmp/exercism-abap-runner-gYJKhk/compiled/cl_abap_unit_assert.clas.mjs:223:9)
    at async ltcl_itab_nesting.test_nesting (file:///tmp/exercism-abap-runner-gYJKhk/compiled/zcl_itab_nesting.clas.testclasses.mjs:234:5)
    at async Function.run (file:///tmp/exercism-abap-runner-gYJKhk/compiled/kernel_unit_runner.clas.mjs:133:11)
    at async run (file:///tmp/exercism-abap-runner-gYJKhk/compiled/_unit_open.mjs:33:17)`

**Resolution 1: traditional loops, easy to understand and debug friendly..**
`
    LOOP AT artists INTO DATA(ls_artist).
      APPEND VALUE #( artist_id = ls_artist-artist_id  artist_name = ls_artist-artist_name ) TO nested_data ASSIGNING FIELD-SYMBOL(<artist>).
      LOOP AT albums INTO DATA(ls_album) WHERE artist_id EQ ls_artist-artist_id.
        APPEND VALUE #( album_id = ls_album-album_id album_name = ls_album-album_name ) TO <artist>-albums ASSIGNING FIELD-SYMBOL(<album>).
        LOOP AT songs INTO DATA(ls_song) WHERE album_id EQ ls_album-album_id.
          APPEND VALUE #( song_id = ls_song-song_id song_name = ls_song-song_name ) TO <album>-songs.
        ENDLOOP.
      ENDLOOP.
    ENDLOOP.`

**Resolution 2: FOR statements**
`    nested_data = VALUE #( FOR ls_artist1 IN artists ( artist_id   = ls_artist1-artist_id
                                                       artist_name = ls_artist1-artist_name
                                                       albums      = VALUE #( FOR ls_album1 IN albums
                                                                     WHERE ( artist_id = ls_artist1-artist_id )
                                                                     ( album_id   = ls_album1-album_id
                                                                       album_name = ls_album1-album_name
                                                                       songs = VALUE #( FOR ls_song1 IN songs
                                                                               WHERE ( album_id = ls_album1-album_id )
                                                                               ( song_id = ls_song1-song_id
                                                                                 song_name = ls_song1-song_name ) ) ) ) ) ).`
   
 Any idea on how to resolve the errors raised by Exercism?

**Comment by bau-mann** [comment]
I get the same error:

```
TypeError: _c.get is not a function
    at FieldSymbol.get (/usr/local/lib/node_modules/@abaplint/runtime/build/src/types/field_symbol.js:54:80)
    at ABAP.templateFormatting (/usr/local/lib/node_modules/@abaplint/runtime/build/src/template_formatting.js:11:23)
    at Function.dump_structure (file:///tmp/exercism-abap-runner-Ew5gGu/compiled/cl_abap_unit_assert.clas.locals.mjs:48:169)
    at async Function.to_string (file:///tmp/exercism-abap-runner-Ew5gGu/compiled/cl_abap_unit_assert.clas.locals.mjs:24:19)
    at async Function.assert_equals (file:///tmp/exercism-abap-runner-Ew5gGu/compiled/cl_abap_unit_assert.clas.mjs:231:19)
    at async Function.assert_equals (file:///tmp/exercism-abap-runner-Ew5gGu/compiled/cl_abap_unit_assert.clas.mjs:223:9)
    at async ltcl_itab_nesting.test_single_artist (file:///tmp/exercism-abap-runner-Ew5gGu/compiled/zcl_itab_nesting.clas.testclasses.mjs:69:5)
    at async Function.run (file:///tmp/exercism-abap-runner-Ew5gGu/compiled/kernel_unit_runner.clas.mjs:133:11)
    at async run (file:///tmp/exercism-abap-runner-Ew5gGu/compiled/_unit_open.mjs:33:17)
```

For both of these code snippets:

```
  METHOD perform_nesting.
    DATA nested_artist TYPE REF TO nested_data.
    LOOP AT artists REFERENCE INTO DATA(artist).
      APPEND CORRESPONDING #( artist->* ) TO nested_data. " <<<
      "APPEND VALUE #( artist_id = '1' 
      "                artist_name = 'abc' ) TO nested_data.
      nested_artist = REF #( nested_data[ artist_id = artist->artist_id ] ).
    ENDLOOP.
  ENDMETHOD.
```

```
  METHOD perform_nesting.
    DATA nested_artist TYPE REF TO nested_data.
    LOOP AT artists REFERENCE INTO DATA(artist).
      "APPEND CORRESPONDING #( artist->* ) TO nested_data.
      APPEND VALUE #( artist_id = '1' 
                      artist_name = 'abc' ) TO nested_data. " <<<
      nested_artist = REF #( nested_data[ artist_id = artist->artist_id ] ).
    ENDLOOP.
  ENDMETHOD.
```

**Comment by larshp** [comment]
better error handling for string template formatting = https://github.com/abaplint/transpiler/pull/890

fix dump in unit test assert = https://github.com/open-abap/open-abap/pull/468

**Comment by larshp** [comment]
try again,

![image](https://user-images.githubusercontent.com/5888506/192772631-daa397eb-3973-4683-8537-04024197b69a.png)

**Comment by bau-mann** [comment]
@larshp Thank you, it works for me now.

**Comment by crazyhenk78** [comment]
@larshp thanks for resolving errors!

Could you please check why test 4 fails with message:
`Expected 'artist_id: 1, artist_name: Godsmack, albums: [itab]', got 'artist_id: 1, artist_name: Godsmack, albums: [itab]'`

Thanks!

**Comment by crazyhenk78** [comment]
@larshp @rich-heilman  could you please check why test 4 for both resolutions (see below) fails with message:
`Expected 'artist_id: 1, artist_name: Godsmack, albums: [itab]', got 'artist_id: 1, artist_name: Godsmack, albums: [itab]'`

Resolution 1: traditional loops, easy to understand and debug friendly..
`
LOOP AT artists INTO DATA(ls_artist). APPEND VALUE #( artist_id = ls_artist-artist_id artist_name = ls_artist-artist_name ) TO nested_data ASSIGNING FIELD-SYMBOL(<artist>). LOOP AT albums INTO DATA(ls_album) WHERE artist_id EQ ls_artist-artist_id. APPEND VALUE #( album_id = ls_album-album_id album_name = ls_album-album_name ) TO <artist>-albums ASSIGNING FIELD-SYMBOL(<album>). LOOP AT songs INTO DATA(ls_song) WHERE album_id EQ ls_album-album_id. APPEND VALUE #( song_id = ls_song-song_id song_name = ls_song-song_name ) TO <album>-songs. ENDLOOP. ENDLOOP. ENDLOOP.
`

Resolution 2: FOR statements
`
nested_data = VALUE #( FOR ls_artist1 IN artists ( artist_id = ls_artist1-artist_id artist_name = ls_artist1-artist_name albums = VALUE #( FOR ls_album1 IN albums WHERE ( artist_id = ls_artist1-artist_id ) ( album_id = ls_album1-album_id album_name = ls_album1-album_name songs = VALUE #( FOR ls_song1 IN songs WHERE ( album_id = ls_album1-album_id ) ( song_id = ls_song1-song_id song_name = ls_song1-song_name ) ) ) ) ) ).
`

**Comment by larshp** [comment]
Album IDs are unique per artist, not globally unique

```abap
    LOOP AT artists INTO DATA(ls_artist).
      APPEND VALUE #( artist_id = ls_artist-artist_id artist_name = ls_artist-artist_name ) TO nested_data ASSIGNING FIELD-SYMBOL(<artist>).
      LOOP AT albums INTO DATA(ls_album) WHERE artist_id EQ ls_artist-artist_id.
        APPEND VALUE #( album_id = ls_album-album_id album_name = ls_album-album_name ) TO <artist>-albums ASSIGNING FIELD-SYMBOL(<album>).
        LOOP AT songs INTO DATA(ls_song) WHERE album_id EQ ls_album-album_id.
          APPEND VALUE #( song_id = ls_song-song_id song_name
= ls_song-song_name ) TO <album>-songs. ENDLOOP.
      ENDLOOP.
    ENDLOOP.
```

![image](https://user-images.githubusercontent.com/5888506/193822732-4fbed781-8b52-42a5-b46f-36546a61255a.png)

**Comment by crazyhenk78** [comment]
Thanks @larshp : 
"artist_id EQ ls_artist-artist_id" condition in  loop over songs was indeed missing..My bad!
Thanks @larshp!

`*  Option 1: traditional loops, easy to understand and debug friendly :-)
    LOOP AT artists INTO DATA(ls_artist).
      APPEND VALUE #( artist_id = ls_artist-artist_id  artist_name = ls_artist-artist_name ) TO nested_data ASSIGNING FIELD-SYMBOL(<artist>).
      LOOP AT albums INTO DATA(ls_album) WHERE artist_id EQ ls_artist-artist_id.
        APPEND VALUE #( album_id = ls_album-album_id album_name = ls_album-album_name ) TO <artist>-albums ASSIGNING FIELD-SYMBOL(<album>).
        LOOP AT songs INTO DATA(ls_song) WHERE artist_id EQ ls_artist-artist_id
                                           AND album_id  EQ ls_album-album_id.
          APPEND VALUE #( song_id = ls_song-song_id song_name = ls_song-song_name ) TO <album>-songs.
        ENDLOOP.
      ENDLOOP.
    ENDLOOP.`

**Comment by crazyhenk78** [comment]
Exercism TypeError resolved by @larshp . Thanks!
