### ISSUE TITLE
I think maybe the FIND commmand does not work in excercism

### ISSUE THREAD

**Issue by TMNielsenApS** [exercism/abap#210]
I'm trying to solve [Atbash Cipher](https://exercism.org/tracks/abap/exercises/atbash-cipher) but so far no luck.

I can't debug on xcercism, but I think I can conclude that the problem is that the following find command does not work even though it works fine in my own SAP system.

        FIND cipher_text+lv_idx(1) IN cipher MATCH OFFSET lv_cipher_idx.

I have so far only written code for the decode method and it looks like this:
```
METHOD decode.    
  DATA: lv_plain_idx  TYPE i VALUE -1,
          lv_cipher_idx TYPE i,
          lv_char(255),
          lv_blank(1) value space.

    DO strlen( cipher_text ) TIMES.
      DATA(lv_idx) = sy-index - 1.
      lv_blank = cipher_text+lv_idx(1).
      if lv_blank = space.
        CONTINUE.
      ELSE.
        FIND cipher_text+lv_idx(1) IN cipher MATCH OFFSET lv_cipher_idx.
        ADD 1 TO lv_plain_idx.
        IF sy-subrc = 0.
          lv_char+lv_plain_idx(1) = plain+lv_cipher_idx(1).
        ELSE.
          lv_char+lv_plain_idx(1) = cipher_text+lv_idx(1).
        ENDIF.
      ENDIF.
    ENDDO.
    plain_text = lv_char.
  ENDMETHOD.
```

additionally I've added to strings to the private section of the class:
```
    DATA: plain  TYPE string VALUE 'abcdefghijklmnopqrstuvwxyz',
          cipher TYPE string VALUE 'zyxwvutsrqponmlkjihgfedcba'.

```

**Comment by larshp** [comment]
one tip for debugging, try reproducing via https://transpiler.abaplint.org

![image](https://user-images.githubusercontent.com/5888506/192799887-43eb8735-ef8b-4350-a582-a3f8c306458c.png)

put the ABAP code in the left editor, and rightmost it the output from WRITE

```abap
data cipher_text type c length 10.
data cipher type c length 10.
data lv_cipher_idx type i.
data lv_idx type i.
cipher_text = '1234567890'.
FIND cipher_text+lv_idx(1) IN cipher MATCH OFFSET lv_cipher_idx.
write lv_cipher_idx.
```

**Comment by larshp** [comment]
seems okay,

![image](https://user-images.githubusercontent.com/5888506/192801431-38c16ba4-8c88-40ff-9b0f-578f308dee27.png)

**Comment by larshp** [comment]
initializing in data,

![image](https://user-images.githubusercontent.com/5888506/192801756-704724e3-6d1d-4d70-baa6-5a9dd2eed2b8.png)

**Comment by larshp** [comment]
try these workarounds:
* use CONSTANTS if the variables are constant
* initialize the value of the variable in the constructor

**Comment by TMNielsenApS** [comment]
Ok, I will try these workarounds, but I don't get any "some exception raised"

![image](https://user-images.githubusercontent.com/98088068/192803647-c7572833-8411-4b9f-973e-b01328fc26b1.png)

**Comment by TMNielsenApS** [comment]
Yes - I changed from DATA to CONSTANTS and now my decode method works.

Thanks Lars.

**Comment by larshp** [comment]
https://github.com/abaplint/transpiler/issues/891 opened

**Comment by larshp** [comment]
yea

I've also added it in https://github.com/exercism/abap/issues/202

there are other worse errors to fix first 😅
