### ISSUE TITLE
state-of-tic-tac-toe icon

### ISSUE THREAD

**Issue by larshp** [exercism/abap#237]
https://exercism.org/tracks/abap/exercises/state-of-tic-tac-toe

wrong/bad icon? this is a standard exercise, it should have a default icon?

**Comment by bau-mann** [comment]
You're right. It's the same way for other tracks, e.g., https://exercism.org/tracks/go/exercises/state-of-tic-tac-toe

I created this issue: exercism/website-icons/issues/130

**Comment by larshp** [comment]
=> https://github.com/exercism/website-icons/issues/130 

closing
