### ISSUE TITLE
ISOGRAM

### ISSUE THREAD

**Issue by mickrig** [exercism/abap#247]
Hi guys,
I have an issue with exercise isogram. It works in ABAP but not on Exercism.
It looks like that the plattform does not know shift_left built-in function
https://help.sap.com/doc/abapdocu_740_index_htm/7.40/en-US/index.htm?file=abenshift_functions.htm
I got following error output:
![image](https://user-images.githubusercontent.com/38348938/198831296-28ec5233-ed88-4971-b0f4-017183d9bb12.png)

Please find my code below.
```abap
CLASS zcl_isogram DEFINITION PUBLIC.

  PUBLIC SECTION.
    METHODS is_isogram
      IMPORTING
        VALUE(phrase)        TYPE string
      RETURNING
        VALUE(result) TYPE abap_bool.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_isogram IMPLEMENTATION.

  METHOD is_isogram.
    result = abap_true.
    phrase = to_lower( phrase ).

    DO strlen( phrase ) TIMES.
      DATA(letter) = phrase(1).
      phrase = shift_left( val = phrase places = 1 ).
      
      IF letter EQ space
      OR letter EQ '-'.
        CONTINUE.
      ENDIF.

      IF find( val = phrase sub = letter ) GT 0.
        result = abap_false.
        EXIT.
      ENDIF.
    ENDDO.
  ENDMETHOD.

ENDCLASS.
```

Thanks in advance.
Michael

**Comment by larshp** [comment]
https://github.com/abaplint/transpiler/pull/959

**Comment by larshp** [comment]
@mickrig try again

![image](https://user-images.githubusercontent.com/5888506/198843320-610d97ee-8fcf-48ec-a8c2-92533c324b74.png)

**Comment by mickrig** [comment]
Thanks Lars, now it works on Exercism.
