### ISSUE TITLE
Exercise Isogram: Test fails online but not in local Editor

### ISSUE THREAD

**Issue by HuprichT** [exercism/abap#259]
Hi, 

currently working on the [Isogram Exercise](https://exercism.org/tracks/abap/exercises/isogram) in Exercism.
Test with string 'Cloud-Application' delivers not expected result:
<img src="https://user-images.githubusercontent.com/45813255/213111005-cfeaa766-c4ac-414a-be44-067d8a62091b.png" width="525" height="300">
![image](https://user-images.githubusercontent.com/45813255/213110123-4acfdd12-a02a-4fd3-8596-bcacbb63dedd.png)

**In local Editor, the Test Case works just fine and returns the expected result = abap_true.**
I'm working on ABAP NW 7.50 SP19.

See below my current implementation:

```abap
CLASS zcl_isogram DEFINITION.

  PUBLIC SECTION.
    METHODS is_isogram
      IMPORTING
        VALUE(phrase)        TYPE string
      RETURNING
        VALUE(result) TYPE abap_bool.
  PROTECTED SECTION.
  PRIVATE SECTION.
  TYPES: BEGIN OF ty_letters,
         letter TYPE c LENGTH 1,
         END OF ty_LETTERS.
  DATA: letters TYPE SORTED TABLE OF ty_letters WITH UNIQUE KEY letter.
ENDCLASS.

CLASS zcl_isogram IMPLEMENTATION.

  METHOD is_isogram.
   DATA(phrase_conv) = to_lower( phrase ).
   DATA(counter) = 0.

   result = abap_true.

   DO strlen( phrase ) TIMES.
    INSERT CONV #( phrase_conv+counter(1) ) INTO TABLE letters.

    IF sy-subrc <> 0.
        result = abap_false.
        RETURN.
   ENDIF.
   counter = counter + 1.
   ENDDO.
  ENDMETHOD.

ENDCLASS.

START-OF-SELECTION.
DATA(obj) = NEW zcl_isogram( ).

IF obj->is_isogram( phrase = 'Cloud-Application' ).
    WRITE: / 'Is Isogram'.
ELSE.
    WRITE: / 'Not an Isogram'.
ENDIF.
```

**Comment by larshp** [comment]
![image](https://user-images.githubusercontent.com/5888506/213113879-85f13504-f83e-491e-a583-595ea1ee2e77.png)

**Comment by larshp** [comment]
one part of the isogram logic is missing in the implementation

check the instructions of the exercise again

plus the test case `is_isogram3`

**Comment by HuprichT** [comment]
> plus the test case `is_isogram3`

thanks for the hint, by inspecting the correct Test Case it has turned out that some implementation was missing and the exercise works as expected

**Comment by larshp** [comment]
cool, closing
