### ISSUE TITLE
 Variable named "case" - Error occured without details

### ISSUE THREAD

**Issue by depth1** [exercism/abap#260]
Hello,

When we declare a variable with the name _"case"_ 
the framework tells us that we have an error but we have no details about it.

**Example**

`DATA case TYPE i.`
`DATA(case) = 1.`

**Illustration**

![error](https://user-images.githubusercontent.com/35033575/213526197-7f180b5d-2621-4836-9626-90faf1eb0bc0.PNG)

**Comment by larshp** [comment]
thanks

https://github.com/exercism/abap-test-runner/pull/177 will now show an error message, when merged

the error message is not great, but better than nothing 😅

**Comment by larshp** [comment]
@depth1 try again

![image](https://user-images.githubusercontent.com/5888506/214321531-c72de8a4-a8ac-4895-8125-0a94ecad423e.png)

**Comment by depth1** [comment]
Oh yeah !
It might be useful to have the info of the line where the declaration is located but hey it's better than nothing at all !
Nice work :)
