### ISSUE TITLE
Package $EXERCISM_DIFFERENCE-OF-SQUARES exceeds ABAP 30-characters name limit

### ISSUE THREAD

**Issue by Ennowulff** [exercism/abap#264]
What can I do?
local package $exercism already is quite short, isn't it?
What Package names do you use that it works?
Thanks
Enno

**Comment by larshp** [comment]
there is a discussion in one of the PRs

IMHO, we can provide a different repository for _students_ to easily download the exercises

for _authors_ of new exercises, its not possible to use exclusively abapGit anyho, as there are duplicate filenames to be created, plus markdown/json files to be edited
