### ISSUE TITLE
Instructions for Two-fer excercise ambiguous

### ISSUE THREAD

**Issue by kartefact** [exercism/abap#267]
The instruction has the line: "If your friend likes cookies, and is named..." but the tests only check for the names and there's no input for whether that friend "likes" cookies or not. Either the instruction needs to be modified for specifying that there's no check for "liking the cookie or the tests have to be modified to check for both "liking" and the "name".

**Comment by mbtools** [comment]
Please provide feedback on the instructions here: 
https://github.com/exercism/problem-specifications/issues
