### ISSUE TITLE
Kindergarten Garden specs

### ISSUE THREAD

**Issue by mbtools** [exercism/abap#56]
Looking at the JS version of the exercise, there should be an ABAP constructor and constants for the input and output. The point is that students should focus on the logic, not typing these values.

https://github.com/exercism/javascript/blob/main/exercises/practice/kindergarten-garden/kindergarten-garden.js

**Comment by marianfoo** [comment]
Yes, I have thought about that too.
Thought that is still a small exercise how to build that in ABAP, you can of course already specify.
I only looked at Ruby exercises and there they were not given.

**Comment by marianfoo** [comment]
@mbtools Oh, I thought the criticism was valid. Don't you want to change it?

**Comment by mbtools** [comment]
it's not important. devs will figure out how to do it ;-)
