### ISSUE TITLE
Scrabble Score - Error in ABAPopen but not in ABAP Backend

### ISSUE THREAD

**Issue by jung-thomas** [exercism/abap#69]
This might be the same or a similar issue to #68 because I'm using a similar FOR loop and COND switch. 
The solution tests fine in an ABAP backend system (ABAP Cloud Trial) 
![image](https://user-images.githubusercontent.com/12159356/153670326-880daa02-3990-4c09-8fc8-951d9ecefa21.png)

But the same in the Exercism Web Editor/Solution Validator says the statement doesn't exist in ABAPopen-abap
![image](https://user-images.githubusercontent.com/12159356/153670432-95c5ac15-1e76-4a81-97f5-8dc7d1e505d4.png)

Here is the code of the solution I'm trying 

```abap
    result =
  REDUCE string( INIT s = 0
                 FOR  i = 0 WHILE i < strlen( input )
                 NEXT s += COND i( LET current_val = to_upper( input+i(1) ) IN
                 WHEN contains( val = 'AEIOULNRST' sub = current_val ) THEN 1
                 WHEN contains( val = 'DG' sub = current_val ) THEN 2
                 WHEN contains( val = 'BCMP' sub = current_val ) THEN 3
                 WHEN contains( val = 'FHVWY' sub = current_val ) THEN 4
                 WHEN contains( val = 'K' sub = current_val ) THEN 5
                 WHEN contains( val = 'JX' sub = current_val ) THEN 8
                 WHEN contains( val = 'QZ' sub = current_val ) THEN 10
                 ELSE 0
                 ) ).
```

**Comment by larshp** [comment]
yeah, thanks, there are some problems with the FOR

**Comment by larshp** [comment]
running locally, update of runner pending

![image](https://user-images.githubusercontent.com/5888506/159866029-1df4e79f-ee14-41e3-9358-b0bdf390c0fe.png)

**Comment by larshp** [comment]
@jung-thomas try again

**Comment by larshp** [comment]
closing, no reply

**Comment by jung-thomas** [comment]
Sorry about - did retest and it worked. Just forgot to return here to close. Thanks!
