### ISSUE TITLE
ABAP += and -= results in Statement does not exist in ABAPopen-abap

### ISSUE THREAD

**Issue by jung-thomas** [exercism/abap#70]
The usage of ABAP += and -= (which passes a syntax check and executes in a backend system) results in this error when executing in Exercism.
./zcl_kindergarten_garden.clas.abap[60, 7] - Statement does not exist in ABAPopen-abap(or a parser error), "second_offset" (parser_error) [E]
./zcl_kindergarten_garden.clas.abap[62, 7] - Statement does not exist in ABAPopen-abap(or a parser error), "second_offset" (parser_error) [E]
abaplint: 2 issue(s) found

I replace this with the long form syntax and then it works correctly:
```abap
*    IF second_offset = 0.
*      second_offset += 1.
*    ELSE.
*      second_offset -= 1.
*      first_offset = second_offset - 1.
*    ENDIF.
    IF second_offset = 0.
      second_offset = second_offset + 1.
    ELSE.
      second_offset = second_offset - 1.
      first_offset = second_offset - 1.
    ENDIF.
```

**Comment by larshp** [comment]
thanks, not downported yet in abaplint 😄

**Comment by larshp** [comment]
implemented in https://github.com/abaplint/abaplint/pull/2410

exercism updated in https://github.com/exercism/abap-test-runner/pull/47

try again on the website

**Comment by jung-thomas** [comment]
Tested - works great now. Thanks!
