### ISSUE TITLE
Hello World - Classic vs ADT

### ISSUE THREAD

**Issue by mbtools** [exercism/abap#76]
Current hello-world exercise uses ADT interface which requires some explanation for newbies and students solving directly on the website.

1. Change description of current "Hello World" to "Hello World (Modern)" and extend instructions to explain ADT interface
2. Add "Hello World (Classic)" using class without ADT interface

**Comment by pokrakam** [comment]
Just a thought: If none of the other exercises use the ADT interface, does it even make sense to do so here? 
Why not just use a method with a RETURNING parameter just like all other exercises and most languages? 
I remember there was a small debate about it on slack and the ADT console interface seemed like a good idea at the time but in retrospect I don't think so.

If we extend the explanation to tell the user that there is an output that they might see if they weren't using this website but even with a real SAP system they might or might not see depending on which IDE they were using, ands therefore might have to write using different syntax is possibly a bit confusing and maybe a bit negative impression. 

Almost all other languages use a function or method that returns a hello world result as far as I can tell. 
https://github.com/exercism/javascript/blob/main/exercises/practice/hello-world/.meta/proof.ci.js
https://github.com/exercism/cpp/blob/main/exercises/practice/hello-world/.meta/example.cpp
https://github.com/exercism/x86-64-assembly/blob/main/exercises/practice/hello-world/.meta/example.asm
https://github.com/exercism/c/blob/main/exercises/practice/hello-world/.meta/example.c

A syntactically similar language to ABAP is PL/SQL and that uses functions too. 
https://github.com/exercism/plsql/blob/main/exercises/practice/hello-world/.meta/example.plsql

One exception is bash, but I think that's a special case.
https://github.com/exercism/bash/blob/main/exercises/practice/hello-world/.meta/example.sh

**Comment by larshp** [comment]
yea, change it to a RETURNING

and then the existing can be moved to a "hello world, advanced" exercise
