### ISSUE TITLE
github settings changes -> admin

### ISSUE THREAD

**Issue by mbtools** [exercism/abap#83]
Add a description and link to the ABAP track to the "About" section.

Currently:

![image](https://user-images.githubusercontent.com/59966492/160113764-edd75d14-8429-408e-a36f-7cf0a4d2919f.png)

Javascript Example:

![image](https://user-images.githubusercontent.com/59966492/160113722-ee4c67ca-abd8-4495-83bc-55e6a78857cd.png)

**Comment by marianfoo** [comment]
@larshp do you have the rights to do this?
Otherwise might ask Erik

**Comment by larshp** [comment]
no, I dont have access

perhaps we should gather a list

* set branch `main` to protected
* remove the projects view
* remove the wiki view

**Comment by larshp** [comment]
@ErikSchierboom can you help updating the settings for this repository? see list in above comment

**Comment by ErikSchierboom** [comment]
@larshp I only have permissions to set the website link. The rest must be done by @iHiD

**Comment by iHiD** [comment]
All should be done. Please confirm and let me know if anything else needs doing. I also add configlet as a compulsory check. Is there some CI that should also be compulsory?

**Comment by mbtools** [comment]
Alright! Thanks 👍
