### ISSUE TITLE
tracks.exercism.io, Track maintenance

### ISSUE THREAD

**Issue by mbtools** [exercism/abap#85]
How do we get ABAP added to https://tracks.exercism.io/?

**Comment by larshp** [comment]
🤷‍♂️

**Comment by mbtools** [comment]
https://github.com/exercism/tracks-maintenance-dashboard/pull/90

**Comment by SleeplessByte** [comment]
Once this is green, it should be up: https://github.com/exercism/tracks-maintenance-dashboard/actions/runs/2112344664

**Comment by larshp** [comment]
ABAP now listed, https://tracks.exercism.io
