### ISSUE TITLE
Error occurred in "Scrabble Score"

### ISSUE THREAD

**Issue by suynwa** [exercism/abap#91]
```abap
check INPUT is not initial.
    RESULT = COUNT( VAL = INPUT CASE = ABAP_FALSE REGEX = `[AEIOULNRST]` )
             + 2 * COUNT( VAL = INPUT CASE = ABAP_FALSE REGEX = `[DG]` )
             + 3 * COUNT( VAL = INPUT CASE = ABAP_FALSE REGEX = `[BCMP]` )
             + 4 * COUNT( VAL = INPUT CASE = ABAP_FALSE REGEX = `[FHVWY]` )
             + 5 * COUNT( VAL = INPUT CASE = ABAP_FALSE REGEX = `[K]` )
             + 8 * COUNT( VAL = INPUT CASE = ABAP_FALSE REGEX = `[JX]` )
             + 10 * COUNT( VAL = INPUT CASE = ABAP_FALSE REGEX = `[QZ]` ).
```
I am getting an error when trying to run the tests for the above solution to the "Scrabble Score". If i understand correctly ABAP version 754 is recommended. 

The above code compiles correctly on my ABAP system

**Comment by larshp** [comment]
reproduced as

```
DATA cnt TYPE i.
cnt = count( val = 'aabb' case = abap_false regex = `[AEIOULNRST]` ).
WRITE cnt.
```

![image](https://user-images.githubusercontent.com/5888506/160598732-1acc76f3-1607-4ba3-8d7b-ef93e5c134a1.png)

**Comment by larshp** [comment]
https://github.com/abaplint/transpiler/pull/671/commits/386da94041bd50c29845e756c647ca4f6e81e301

**Comment by larshp** [comment]
@suynwa try again, 

![image](https://user-images.githubusercontent.com/5888506/160608856-4b877df9-f4eb-4e9d-ab33-d72cfbf9343f.png)

**Comment by larshp** [comment]
PCRE: no, not as of now
