### ISSUE TITLE
Error in "High Scores" -> Could not resolve top CL_ABAP_ITAB_UTILITIES, resolveTypeChain (unknown_types)

### ISSUE THREAD

**Issue by suynwa** [exercism/abap#93]
When trying to run the tests for the below code

``` abap

  private section.
    data SCORES_LIST type INTEGERTAB.

    methods GET_TOP_SCORE_UPTO
      importing
        HITS            type I
      returning
        value(R_RESULT) type ZCL_HIGH_SCORES=>INTEGERTAB.
...
  method PERSONALBEST.
    check SCORES_LIST is not initial.
    data(TOP_SCORES) = GET_TOP_SCORE_UPTO( 1 ).
    RESULT = TOP_SCORES[ 1 ].
  endmethod.

  method PERSONALTOPTHREE.
    RESULT = GET_TOP_SCORE_UPTO( 3 ).
  endmethod.

  method GET_TOP_SCORE_UPTO.
    data SORTED_INDICES type CL_ABAP_ITAB_UTILITIES=>VIRTUAL_SORT_INDEX.
    SORTED_INDICES  = CL_ABAP_ITAB_UTILITIES=>VIRTUAL_SORT(
                          IM_VIRTUAL_SOURCE = value #( ( SOURCE     = ref #( SCORES_LIST )
                                                         COMPONENTS = value #( ( NAME       = |TABLE_LINE|
                                                                                 DESCENDING = 'X' ) ) ) ) ).

    R_RESULT = value #( for INDEX in SORTED_INDICES to HITS
                        ( SCORES_LIST[ INDEX ] ) ).
  endmethod.
```
i am getting the following error:
![image](https://user-images.githubusercontent.com/31508041/160288201-7c2343cc-ccaa-4000-a16a-fc8c4320bfcd.png)

I want to sort the attribute SCORES_LIST virtually, since i want to preserve the order of the constructor input SCORES.

**Comment by pokrakam** [comment]
The issue is the use of CL_ITAB_UTILITIES, which doesn't exist. This is pure ABAP, no SAP system behind it. Use only the syntax found in the online help.

**Comment by suynwa** [comment]
Thanks Mike! I kinda guessed that system classes CL_ABAP* might not be available. 

I tried the following workaround w/o the virtual sorting:

``` abap
  method GET_TOP_SCORE_UPTO.
    data(SORTED_SCORES) = SCORES_LIST.
    sort SORTED_SCORES by TABLE_LINE descending.
    RESULT = value #( ( lines of SORTED_SCORES to HITS ) ).
  endmethod.
``` 
but got another error:
![image](https://user-images.githubusercontent.com/31508041/160331157-ef555e61-d452-4aa6-a98d-48a4bc8e61f4.png)

I assume that the LINES OF...FROM...TO is not yet implemented in the transpiler? 🤔

**Comment by larshp** [comment]
as of now, CL_ABAP_ITAB_UTILITIES is not released in Steampunk

https://github.com/abaplint/transpiler/issues/670 opened

**Comment by pokrakam** [comment]
Heh, didn't know `lines` can be used inside a `value` constructor, learnt something today. 
But in that case I wonder why you need `value`, can't you do a regular assignment? 
`result = lines of sorted_scores to hits.`
Should work because index access worked in my solution, though I used `delete from`
https://exercism.org/tracks/abap/exercises/high-scores/solutions/pokrakam

**Comment by suynwa** [comment]
I am getting the same error when i use the verbose variant 
```abap
insert lines of SORTED_SCORES to HITS into table RESULT.
```

**Comment by larshp** [comment]
some part fix, https://github.com/abaplint/abaplint/pull/2464/commits/9283f5844cbdd118121ad4111590e0820a156e0a

**Comment by larshp** [comment]
@suynwa try again

using CL_ABAP_ITAB_UTILITIES is not supported, and we dont want to support it as of now, as its not released by SAP(dont know why its not released)

in case of error, can you help posting the complete solution here?

**Comment by larshp** [comment]
https://github.com/abaplint/abaplint/pull/2468

**Comment by larshp** [comment]
@suynwa above example does not match the unit tests in exercism? see https://github.com/exercism/abap/blob/main/exercises/practice/high-scores/zcl_high_scores.clas.abap

**Comment by suynwa** [comment]
@larshp I had posted only the part of the solution which had LINES OF, sorry for the confusion. 

Below is the complete code:

```abap
CLASS zcl_ssa_high_scores DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC.

  PUBLIC SECTION.
    TYPES integertab TYPE STANDARD TABLE OF i WITH EMPTY KEY.
    METHODS constructor
      IMPORTING
        scores TYPE integertab.

    METHODS list_scores
      RETURNING
        VALUE(result) TYPE integertab.

    METHODS latest
      RETURNING
        VALUE(result) TYPE i.

    METHODS personalbest
      RETURNING
        VALUE(result) TYPE i.

    METHODS personaltopthree
      RETURNING
        VALUE(result) TYPE integertab.
  PROTECTED SECTION.
  PRIVATE SECTION.
    DATA scores_list TYPE integertab.

    METHODS get_top_score_upto
      IMPORTING
        hits          TYPE i
      RETURNING
        VALUE(result) TYPE zcl_ssa_high_scores=>integertab.

ENDCLASS.


CLASS zcl_ssa_high_scores IMPLEMENTATION.
  METHOD constructor.
    scores_list = scores.
  ENDMETHOD.

  METHOD list_scores.
    result = scores_list.
  ENDMETHOD.

  METHOD latest.
    CHECK scores_list IS NOT INITIAL.
    result = scores_list[ lines( scores_list ) ].
  ENDMETHOD.

  METHOD personalbest.
    CHECK scores_list IS NOT INITIAL.
    DATA(top_scores) = get_top_score_upto( 1 ).
    result = top_scores[ 1 ].
  ENDMETHOD.

  METHOD personaltopthree.
    CHECK scores_list IS NOT INITIAL.
    result = get_top_score_upto( 3 ).
  ENDMETHOD.

  METHOD get_top_score_upto.
    DATA(sorted_scores) = scores_list.
    SORT sorted_scores BY table_line DESCENDING.
    result = VALUE #( ( LINES OF sorted_scores TO hits ) ).
  ENDMETHOD.
ENDCLASS.
```

**Comment by larshp** [comment]
@suynwa try again, note that the code from your comment does not match exercism due to the naming

![image](https://user-images.githubusercontent.com/5888506/160828480-866b7fa8-2596-434b-affa-7c168b103c5d.png)

**Comment by suynwa** [comment]
Works now with LINES OF...TO 👍
