### ISSUE TITLE
How do we migrate published exercises to concepts?

### ISSUE THREAD

**Issue by pokrakam** [exercism/abap#98]
Probably a question for @ErikSchierboom : We've published a couple of exercises that appear as concepts in other tracks as practice exercises. 

Can they easily be converted to concepts? Is it a simple matter of moving it to the right folders once all the documentation and other structures are done, or do we need to obsolete and recreate? I guess it depends if this affects students' completed exercises?

**Comment by ErikSchierboom** [comment]
> Can they easily be converted to concepts? Is it a simple matter of moving it to the right folders once all the documentation and other structures are done, or do we need to obsolete and recreate? I guess it depends if this affects students' completed exercises?

Oh, that's a situation unknown to me actually (nobody has done this before). In principle, I _think_ moving them to the right location would do the trick (@iHiD is that correct), but unfortunately the situation is not so simple. Concepts exercises should form a curriculum, meaning there should be at least 7+ of them and there should be a well-thought out progression from one concept exercise to the next. Let me know if this is something you want to work on.

**Comment by marianfoo** [comment]
I suspect it's a simple change in config.json like [here ](https://github.com/exercism/abap/pull/89/files#diff-587cb980af76fdc7e52369fd0b9d926dff266976b6f8ac631e358fecc49ff8cf)plus move it to the folder.
But first we would need to write the basics to continue.
That the concept exercises are currently under the exercises does not trouble me for now.

**Comment by ErikSchierboom** [comment]
@marianfoo Just in case you've missed it, it is slightly more complex than that. See my above comment.

**Comment by pokrakam** [comment]
Yes, concepts would be great, but it was clear that a coherent concept structure is significantly more work therefore we just published everything as practice to get the track up and running. 

I assumed it would be simple to refactor later using the json configs, but as I got deeper into it I realised it may not be a straightforward cut-n-paste job, hence the question.

**Comment by ErikSchierboom** [comment]
Right. So what I would do, is to leave them as practice exercise for the moment. Once some other concept exercises have been added, those practice exercises can be converted to concept exercises by updating them and the config.

**Comment by pokrakam** [comment]
Thanks for the info, we shall do just that!
