### ISSUE TITLE
Can i create randomized tests?

### ISSUE THREAD

**Issue by marianfoo** [exercism/abap#99]
As seen here, the user was quiet smart (or lazy) and just used the solution as reference to create his method.
Is it possible to create a randomizer and hide it? Because the testclasses are shown to the user.
could not find something in the doc https://exercism.org/docs/building/tracks/practice-exercises

https://exercism.org/tracks/abap/exercises/scrabble-score/solutions/karlojkessler
![image](https://user-images.githubusercontent.com/13335743/160794875-d73bf45b-cc62-49b3-940e-8e89da4b59b9.png)

**Comment by larshp** [comment]
heh 😁 

well, its up to the student if that person wants to learn something or not. It is kind of a TDD approach, the minimal and simplest solution to pass the unit tests, however it doesnt solve the problem as such

**Comment by pokrakam** [comment]
I agree with @larshp that someone is only cheating themselves.
IMHO unit tests are a valuable part of the learning experience. For the JS track I have them open to the side when doing the exercise and code up the solution for one or two tests at a time - proper TDD style. Literally start with `return 0;` to pass the 'is empty' test, then hardcode to pass the next test, then add logic, pass, next test, .. and so on.

**Comment by pokrakam** [comment]
We could code up a randomiser in the test, but then we'd have to put the solution code into the test too in order to validate our random result, so that's no good. 
The same issue exists in all the tracks so I think this is not something to worry about.

**Comment by marianfoo** [comment]
Essentially too much work for too little benefit
